### PR TITLE
 replace attr.Factory()

### PR DESCRIPTION
**Pull request by JefffHofffman**
#1094

### CODE REVIEW

**Comment by njsmith** [comment]
What the heck? Why does it say I closed this? I have no idea what's going on there.

**Comment by JefffHofffman** [comment]
Sorry for the mixup.  My first PR was for a bad branch (classic goof creating branch with wrong parent)  .  I deleted the branch and created attr-factory2 with the proper contents.  Is there a better way for me to correct such a situation?  Unrelated to the mystery close?

**Comment by pquentin** [comment]
Thank you!

**Comment by njsmith** [comment]
> Sorry for the mixup. My first PR was for a bad branch (classic goof creating branch with wrong parent) . I deleted the branch and created attr-factory2 with the proper contents. Is there a better way for me to correct such a situation?

In theory you can always fix a mistake by doing some kind of git rebasing and force pushing to update your branch to contain the commits you wanted. In practice, sometimes it's easier to throw it away and start over. And there's no shame in doing so – we're not going to run out of PR numbers or anything :-)

> #1094

Handy tip: if you instead write `closes #1094` or `fixes: #1094` or [a few other variations](https://help.github.com/en/articles/closing-issues-using-keywords), then the issue gets automatically closed when the PR is merged. Not a big deal, but one less thing to remember :-)

Anyway! As noted in [our contributing documentation](https://trio.readthedocs.io/en/latest/contributing.html#joining-the-team), we'd love to have more contributions so I just sent you an invitation to join the team.

**Pull request merged**
