### PR TITLE
print out the slowest 10 pytest tests

### PR DESCRIPTION
**Pull request by jakkdl**
Cannot reproduce why pypy takes upwards of 10 minutes (seems isolated to mac/windows?), and given how massive the testing log is anyway this probably doesn't hurt to have running in CI.

### CODE REVIEW

**Comment by jakkdl** [comment]
Windows pypy-3.9-nightly:
Total: 6:54
```
27.46s call     _tests/test_ssl.py::test_renegotiation_randomized[tls13]
26.09s call     _tests/test_ssl.py::test_renegotiation_randomized[tls12]
25.56s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio]
20.53s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio]
18.67s call     _tests/test_dtls.py::test_handshake_over_terrible_network
14.72s call     _core/_tests/test_multierror.py::test_ipython_custom_exc_handler
12.48s call     _tests/test_threads.py::test_run_in_worker_thread_limiter[False-False-10]
9.96s call     _tests/test_socket.py::test_many_sockets
9.69s call     _tests/test_threads.py::test_run_in_worker_thread_limiter[False-True-10]
9.46s call     _core/_tests/test_multierror.py::test_ipython_exc_handler
```
macOS pypy-3.9-nightly
Total: 9:13
```
 98.88s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio]
34.24s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio]
31.43s call     _tests/test_ssl.py::test_renegotiation_randomized[tls13]
30.25s call     _tests/test_ssl.py::test_renegotiation_randomized[tls12]
22.69s call     _tests/test_dtls.py::test_handshake_over_terrible_network
17.32s call     _core/_tests/test_multierror.py::test_ipython_custom_exc_handler
14.61s call     _tests/test_highlevel_socket.py::test_SocketStream_send_all
9.25s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio.lowlevel]
7.93s call     _tests/test_socket.py::test_many_sockets
7.50s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pylint-trio]
```
macOS pypy-3.10-nightly
Total: 9:09
```
 ============================= slowest 10 durations =============================
31.88s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio]
31.78s call     _tests/test_ssl.py::test_renegotiation_randomized[tls13]
31.75s call     _tests/test_dtls.py::test_handshake_over_terrible_network
30.83s call     _tests/test_ssl.py::test_renegotiation_randomized[tls12]
25.50s call     _core/_tests/test_multierror.py::test_ipython_custom_exc_handler
20.00s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio]
14.78s call     _tests/test_highlevel_socket.py::test_SocketStream_send_all
10.70s call     _tests/test_dtls.py::test_invalid_cookie_rejected
9.84s call     _core/_tests/test_multierror.py::test_ipython_imported_but_unused
8.91s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pylint-trio]
```
and for comparison

Ubuntu pypy-3.9
Total: 4:04
```
17.49s call     _tests/test_ssl.py::test_renegotiation_randomized[tls13]
17.24s call     _tests/test_ssl.py::test_renegotiation_randomized[tls12]
16.05s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio]
10.63s call     _tests/test_dtls.py::test_handshake_over_terrible_network
9.48s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio]
8.88s call     _core/_tests/test_multierror.py::test_ipython_custom_exc_handler
4.54s call     _tests/test_socket.py::test_many_sockets
4.10s call     _core/_tests/test_multierror.py::test_ipython_exc_handler
4.02s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio.lowlevel]
3.76s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pylint-trio]
```
Ubuntu pypy-3.9-nightly: 4:38

Ubuntu pypy-3.10: 6:11
```
============================= slowest 10 durations =============================
27.68s call     _tests/test_ssl.py::test_renegotiation_randomized[tls13]
27.04s call     _tests/test_ssl.py::test_renegotiation_randomized[tls12]
26.05s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio]
16.59s call     _tests/test_dtls.py::test_handshake_over_terrible_network
13.50s call     _core/_tests/test_multierror.py::test_ipython_custom_exc_handler
10.10s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio]
7.79s call     _tests/test_socket.py::test_many_sockets
6.25s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio.lowlevel]
6.05s call     _core/_tests/test_multierror.py::test_ipython_exc_handler
5.97s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pylint-trio]
```
Ubuntu pypy-3.10-nightly: 3:59

macOS 3.9: 1:42
```
 ============================= slowest 10 durations =============================
11.99s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio]
6.43s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[mypy-trio]
4.47s call     _tests/test_exports.py::test_static_tool_sees_class_members[jedi-trio]
3.98s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio.abc]
3.78s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio.lowlevel]
3.32s call     _tests/test_ssl.py::test_renegotiation_randomized[tls12]
3.24s call     _tests/test_ssl.py::test_renegotiation_randomized[tls13]
3.19s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio.testing]
3.15s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio.to_thread]
2.57s call     _tests/test_exports.py::test_static_tool_sees_all_symbols[pyright_verifytypes-trio.from_thread]
```
windows 3.9, x64: 4:09

**Comment by jakkdl** [comment]
disabling test_static_tools on pypy+mac/win would save ~2 minutes (as it's the max that matters), but I'm leaning towards setting pypy+win/mac as not required for merging. pypy+ubuntu and normal win/mac runs should catch 99% of errors anyway, and in case a PR has failed pypy+win/mac at some point you're going to wait for the full results anyhow

**Comment by TeamSpen210** [comment]
This CI run actually failed, by hitting the 15 minute mark for Mac 3.9...
https://github.com/python-trio/trio/actions/runs/5925251140/attempts/1

**Comment by jakkdl** [comment]
> This CI run actually failed, by hitting the 15 minute mark for Mac 3.9... https://github.com/python-trio/trio/actions/runs/5925251140/attempts/1

that one seems to be a strange one-off though, on rerun it passed in 3 minutes (though that's still twice as much as above)

**Comment by jakkdl** [comment]
> but I'm leaning towards setting pypy+win/mac as not required for merging.

this seems ... non-trivial, unless you add >100 lines to `ci.yml` and break out pypy runs into separate actions

**Comment by TeamSpen210** [comment]
Perhaps something that might help in tracking what's going on is to split up the shell script / move the calls into the GitHub Actions configuration. Then we'd get durations of each individual step. Or just make it print out timestamps so we can do it manually.

**Comment by jakkdl** [comment]
> Perhaps something that might help in tracking what's going on is to split up the shell script / move the calls into the GitHub Actions configuration. Then we'd get durations of each individual step. Or just make it print out timestamps so we can do it manually.

IME it's just `pytest` that's taking forever, though in the mac3.9 case it might've been something else.

**Review by TeamSpen210 — APPROVED** [review]

**Pull request merged**
