### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by smurfix**

### CODE REVIEW

**Comment by smurfix** [comment]
598 is already part of his.

**Comment by pquentin** [comment]
@smurfix That was my point, we included a commit in the release that has not been approved yet

**Comment by pquentin** [comment]
I guess the main benefit is that you can easily see on GitHub all the commits that will make it into the release. I think this workflow is pretty standard in the corporate world and is named Gitflow, but that does not mean we have to adopt it

@smurfix thoughts?

**Comment by pquentin** [comment]
(It's also surprising that trio was released even though this pull request has not been merged yet)

**Comment by njsmith** [comment]
Huh, I forgot that gitflow actually does this.

Reading through some of the posts about it, I think their release branch stuff is designed to support a slow-release workflow, where the mainline development branch isn't always releasable, releases are rare, and each release involves some stabilization ceremony. And also maybe your git repo is your release distribution mechanism, rather than using something like PyPI. That's a valid approach, but I'd rather move more towards a quick-release low-ceremony model (like we discussed some in #220), and the canonical way to get our latest release is to check PyPI, so a `release` branch is redundant (violates DRY). So... I don't think having a release branch provides much value here.

**Comment by pquentin** [comment]
Sounds good 👍 

So that means we should close this PR and delete the release branch?

**Comment by njsmith** [comment]
This has been sitting for a while with no followups, so I guess I'm going to go ahead and do what I said!

**Pull request closed without merging**
