### PR TITLE
more small tutorial fixes (take 2)

### PR DESCRIPTION
**Pull request by jab**
- Fix outdated "no HTTP library yet" comment
- Fix typo (s/mean time/meantime)

### CODE REVIEW

**Comment by njsmith** [comment]
This is an extremely finicky and unimportant issue, but since it comes up a lot I guess it's still worth mentioning: despite what you may have heard, the basic "make a hyperlink please" syntax in ReST uses *two* trailing underscores. If you use just one trailing underscore, then ReST treats it as, I don't even know, defining a term or something, so if your document happens to have two links with the same text and different targets, ReST freaks out. To avoid all this nonsense, it's a good habit to use the double underscores everywhere. (See the other links in the docs for examples.)

**Comment by jab** [comment]
Good catch, thanks! Amended in 83a7fc0.

**Comment by jab** [comment]
@njsmith Happy to work up a PR integrating an example like this into the tutorial if that would be helpful, or maybe even just a quick line like the following?
> For another example, check out how you can build an [HTTP CONNECT proxy on top of Trio](https://github.com/jab/trio_http_proxy/blob/master/trio_http_proxy.py) in about 70 lines of code.

**Comment by jab** [comment]
Cool you've been collecting examples in #472 (hadn't seen that), and super cool to see your talk (hadn't seen that either) – live coding happy eyeballs in 40 lines was amazing! Reassuring to see that my HTTP CONNECT proxy example has the same basic structure as your TCP proxy example too. On that note, I think the TCP proxy example is great for its simplicity, so definitely worth including too, but even with the change to redirect to httpbin, I'm not sure the payoff comes close – like when I saw that I could point my browser through this tiny 60-line proxy I'd just written with Trio, and browsing any HTTPS site (including streaming YouTube) just worked, it felt like a super power.
screen shot 2018-04-16 at 08 01 12
For whatever it's worth 😊

P.S. I saw 0.4 just came out, so I reworked the CONNECT example to use the new contextvar support instead of passing custom `log` functions around. Nice work on 0.4!

**Comment by njsmith** [comment]
Okay, using the trio talk on youtube as the demo URL definitely wins an extra prize for slickness :-)

**Pull request merged**
