### PR TITLE
fix B904

### PR DESCRIPTION
**Pull request by jakkdl**
this snuck in with some PR, I blame having half a dozen tests failing currently.

### CODE REVIEW

**Comment by A5rocks** [comment]
I'm confused cause formatting check should block merge nowadays! But whatever.

**Comment by A5rocks** [comment]
(could you update `ruff check` invocation to use `--output-format` instead of `--format`?)

**Review by A5rocks — APPROVED** [review]
Looks good. Still spooky that this snuck by.

But makes sense about the automerge thing actually.

**Comment by A5rocks** [comment]
We could try out GitHub merge queue after the next release (don't want workflow changes before then, ofc) maybe

**Comment by jakkdl** [comment]
> We could try out GitHub merge queue after the next release (don't want workflow changes before then, ofc) maybe

ooh, that looks fancy. This crazy pace of PRs per day can't be kept up that much longer though, and there's only so many checks in ruff that can be enabled.

**Comment by jakkdl** [comment]
oh, I don't seem to be able to merge this due to failing checks. I think it might never have been blocking before?

**Comment by A5rocks** [comment]
If this is due to a flakey test I think we should rerun it cause any fix to the flakey test (a new PR, presumably) will need this fix too!

**Review by CoolCat467 — APPROVED** [review]

**Pull request merged**
