### PR TITLE
Stop failing CI upon codecov error 503

### PR DESCRIPTION
**Pull request by A5rocks**
https://github.com/python-trio/trio/pull/3172 took 5 attempts to merge.......

cc @jakkdl

### CODE REVIEW

**Review by CoolCat467 — APPROVED** [review]

**Comment by webknjaz** [comment]
This would make Codecov less reliable. It'd be better to figure out the version bump.

**Comment by CoolCat467** [comment]
While I agree that it's unfortunate that this would make Codecov less reliable, I think stopping pull requests from going through just because Codecov is buggy is a worse in the end.

**Comment by A5rocks** [comment]
> This would make Codecov less reliable. It'd be better to figure out the version bump.

Does a new uploader really decrease the amount of 503s codecov returns? I note that the failures I checked were due to that, not due to some uploader issue.

**Comment by webknjaz** [comment]
Yes, in my experience, v4 eliminated this problem. I think the retries are better, but also the API is new. I don't really have the stats for v5, though.

The only problem is that my attempt to bump to v5 has some weird coverage computation issue: #3161. I haven't really looked into that. But it's weird that I haven't seen this behavior elsewhere, so my hunch is that it might be related to the structure of the automation in this repo.

**Comment by A5rocks** [comment]
Ok should we merge this as a temporary patch (and a comment saying as much), until someone gets the time to look at v5?

I'm willing to wait a few days just in case we do it quickly but after that I think it's better to be able to get PRs merged on the first attempt. (PR statuses are fine because individual jobs can be rerun, but merge queue needs the rerun every job)

**Comment by jakkdl** [comment]
I think we should merge this as a temp fix due to how massively painful it is to work with.

It's def suboptimal, but /shrug

**Pull request merged**
