### PR TITLE
fix PermissionError due to accessing pthreads upon importing trio

### PR DESCRIPTION
**Pull request by jakkdl**
quickfix for #2688

### CODE REVIEW

**Comment by jakkdl** [comment]
CI fail is due to https://github.com/python-trio/trio/issues/2689#issuecomment-1623572585

**Review by A5rocks — CHANGES_REQUESTED** [review]
I don't really know if this works cause not my kinda thing. Would be happy to merge and get a quick fix out though, just please add a news fragment!

**Comment by A5rocks** [comment]
Actually we can probably ask the original issue reporter to test this. I forgot the syntax to make pip install from a specific branch :(

**Comment by jakkdl** [comment]
ah oops, I wrote a newsfragment but looks like I forgot to add the file

**Comment by jakkdl** [comment]
@chrisbeardy would you mind installing trio from this branch and seeing if it works? https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by chrisbeardy** [comment]
Yep will do, give me a day or so as away for the weekend

**Comment by chrisbeardy** [comment]
Can confirm this imports ok now "on my machine"

**Comment by jakkdl** [comment]
> Can confirm this imports ok now "on my machine"

Awesome! It's the only data point we have about it not working, so that's good enough for me. Feel free to merge and maybe push out a quick bugfix release if the newsfragment looks good (otherwise just edit it directly) @A5rocks

**Review by A5rocks — APPROVED** [review]

**Pull request merged**
