### PR TITLE
Use async_generator.asynccontextmanager

### LINKED ISSUE #418: Remove trio._util.acontextmanager
And switch to using `async_generator.asynccontextmanager` instead.

### PR DESCRIPTION
**Pull request by RazerM**
Resolves #418 

I don't think this needs a newsfragment or a documentation change.

### CODE REVIEW

**Comment by njsmith** [comment]
> I don't think this needs a newsfragment or a documentation change.

Yeah, agreed.

>  +24 −177 

sweet

**Comment by njsmith** [comment]
Thanks!

**Comment by smurfix** [comment]
This change doesn't actually remove `acontextmanager`… why not?

**Comment by njsmith** [comment]
Whoa, whoops. And of course codecov chose this moment to flake out...

**Comment by RazerM** [comment]
@smurfix Oops, PR incoming

**Pull request merged**
