### PR TITLE
Teach trio.socket.fromfd and friends to autodetect socket configuration on Linux

### PR DESCRIPTION
**Pull request by 2easy**
Hi, I'd like to propose this solution to the issue #251 .

### CODE REVIEW

**Comment by 2easy** [comment]
There is problem with `SO_PROTOCOL` on mac, will fix that in a moment.

**Comment by njsmith** [comment]
Hello!

I'm afraid I have misled you and made this much more complicated than it has to be :-(. The code you used for a reference jumps through all kinds of hoops using ctypes, because it's trying to call `getsockopt` on a socket that it only has a fileno for, not a socket object. But on all the versions of Python we care about, we can create a socket object (maybe with incorrect values), and then we can directly use Python's regular `getsockopt` method and skip all that ctypes stuff. Also, the versions of Python we care about have the relevant `SO_WHATEVER` magic constants on the `socket` module on all the systems where they work at all, so we don't need to have the magic numbers like "39" for `SO_DOMAIN`. (And besides, those magic numbers are only correct for Linux.)

So my suggestion would be to delete all the ctypes stuff, and instead have a function like this, that takes whatever the user gave us, fixes it up as best we can (which might be more or less depending on the OS), and returns the fixed up values.

```python
def _fix_attrs_for_fileno(family, type, proto, fileno):
    # Wrap the raw fileno into a socket object
    sockobj = _stdlib_socket.socket(fileno=fileno)
    try:
        if hasattr(socket, "SO_DOMAIN"):
            family = sockobj.getsockopt(SOL_SOCKET, SO_DOMAIN)
        if hasattr(socket, "SO_TYPE"):
            type = sockobj.getsockopt(SOL_SOCKET, SO_TYPE)
        if hasattr(socket, "SO_PROTOCOL"):
            proto = sockobj.getsockopt(SOL_SOCKET, SO_PROTOCOL)
    finally:
        # Unwrap it again, so that sockobj.__del__ doesn't try to close our socket
        sockobj.detach()
    return family, type, proto
```

And then in `fromfd` and `socket` we can do something like:

```python
family, type, proto = _fix_attrs_for_fileno(family, type, proto, fileno)
```

Does that make sense?

**Comment by njsmith** [comment]
@2easy Hey, just wanted to check in to see whether you're still interested in working on this :-)

**Comment by 2easy** [comment]
Sure thing, sorry for the delay. I'll fix it in the evening.

**Comment by njsmith** [comment]
Haven't heard anything for a week, so I'm going to close this for now to take it off the list of active PRs. Feel free to reopen it, or open a new PR, if you do decide to come back to it later! We've all been there :-)

**Pull request closed without merging**
