### PR TITLE
Rebase unix server sockets

### PR DESCRIPTION
**Pull request by CoolCat467**
This PR rebases #1433 so it could be merged

### CODE REVIEW

**Comment by jakkdl** [comment]
hm, something has clearly gone wrong with your rebasing since this is shown as modifying a ton of files.

**Comment by A5rocks** [comment]
It's cause the PR is trying to merge into the unix sockets branch!

**Comment by CoolCat467** [comment]
> hm, something has clearly gone wrong with your rebasing since this is shown as modifying a ton of files.

This is because we are updating the branch it was originally created in, which diverged in 2020.

**Comment by CoolCat467** [comment]
Basically, merging this will resolve the conflicts in #1433, so that it can be reviewed and merged properly. This is a pull request on a pull request.

**Comment by jakkdl** [comment]
Oh, that's fancy! Feels like it might just be simpler to create a new PR including the changes to #1433 meant for merging straight into master though - reviewing this one is close to impossible. Or directly working on #1433

**Comment by CoolCat467** [comment]
Closing as I can now update the `unix-listeners` branch directly

**Pull request closed without merging**
