### PR TITLE
Fix some typos/missing words

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Comment by dimaqq** [comment]
Wow codecov is so confused!

**Comment by brettcannon** [comment]
@dimaqq actually it's accurate since I did add lines to the project that didn't increase the coverage. I believe there's a way to say "ignore these directories" which would solve this.

**Comment by brettcannon** [comment]
@njsmith FYI Codecov has a YAML file you can check in to configure it if you want help tweaking settings.

**Comment by njsmith** [comment]
No, codecov doesn't care about README -- the problem is that there's a branch in `_io_windows.py` that gets taken non-deterministically, so there are 3 lines that are flopping between 2 covered + 1 uncovered versus 1 covered + 2 uncovered :-(.

**Comment by brettcannon** [comment]
@njsmith have you thought about using `# pragma: no cover` for those non-deterministic lines?

**Comment by njsmith** [comment]
It's a legitimate complaint though :-) We should have coverage for both branches, just I got lazy about writing tests for a few bits of code that aren't actually used yet, and are just placeholders for future expansion. (Specifically the non-socket APIs for Windows and Kevent, which I figure will get sorted out properly once we add subprocess support - see also #4, #26, #52.) I have a patch here that I think makes the test coverage deterministic at least though...

**Pull request merged**
