### PR TITLE
Make TracebackException work with Python 3.10.

### PR DESCRIPTION
**Pull request by nascheme**
Pass '_seen' argument as None if empty (on first call). Pass 'compact'
kwarg as needed.

### CODE REVIEW

**Comment by nascheme** [comment]
This might fix #1899.

**Comment by altendky** [comment]
Is this covered in https://github.com/python-trio/trio/pull/1921?

**Comment by nascheme** [comment]
> Is this covered in #1921?

I don't think so.  It fixes the issue with the keyword argument.  However this is a more subtle problem with Python 3.10.  I believe the key commit is 6dfd1734f5b230bb8fbd2a9df806c1333b6652a8 in the cpython repo:
bpo-42848: remove recursion from TracebackException (GH-24158)

The meaning of `_seen = None` is now different than from `_seen = set()`.  If you pass `_seen=set()`, the `__init__` method will not correctly initialize the TracebackException object.

**Comment by altendky** [comment]
I believe we have just implemented different means of passing `None` or `set()`, but that they are the same result?

https://github.com/altendky/trio/blob/c079d3cfdf4b91c76cd9aa376d1ddb76db4d40d7/trio/_core/_multierror.py#L405-L423

I tried a GitHub compare but it isn't showing what I expect. 
 https://github.com/altendky/trio/compare/c079d3cfdf4b91c76cd9aa376d1ddb76db4d40d7...5b3378629c492e5cc458c760d5d3b4df57f75218  So, here is a screenshot of my local diff.  This PR on the left and https://github.com/python-trio/trio/pull/1921 on the right.

image

Aside from the `_seen` bit, it seems like the `kwargs` in this PR are unused.

**Comment by graingert** [comment]
fixed in https://github.com/python-trio/trio/pull/1921 ?

**Comment by graingert** [comment]
ah no this is different

**Comment by Zac-HD** [comment]
I think this has been fixed by the recent change to `exceptiongroup`, @agronholm can reopen if I'm wrong.

**Pull request closed without merging**
