### PR TITLE
Use .png for favicon on RTD

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
Just cleaning up here after this was pointed out over at https://github.com/python-trio/pytest-trio/pull/112#pullrequestreview-508206073.

**Comment by pquentin** [comment]
@altendky Thanks! Can you please rebase from master/merge master into your branch?

**Comment by altendky** [comment]
@pquentin I thought I did for the FreeBSD cache bust and just double checked as well.  What do you see missing?

**Comment by altendky** [comment]
Side note, I personally set repos to require PRs to be up to date to 1) point out when they are not, 2) make sure a real up-to-date build is present before merging, and 3) make the update a button click away.  But Trio usually has relevant reasons for being how it is...

**Comment by pquentin** [comment]
Sorry, my bad. Also, I didn't realize you could configure all that stuff in GitHub

**Pull request merged**
