### PR TITLE
Try out coverage instead of pytest-cov

### PR DESCRIPTION
**Pull request by A5rocks**
Not sure this will work. Fixes https://github.com/python-trio/trio/issues/2645

### CODE REVIEW

**Comment by A5rocks** [comment]
https://github.com/python-trio/trio/pull/2664 has the fix for the Ubuntu 3.11 failure.

**Review by jakkdl — CHANGES_REQUESTED** [review]
Nice, the code in `testing/` is showing up as covered as expected!

Seems like we've lost coverage of `test_multierror_scripts` since they're run with `subprocess.run`. But looks like there's documentation on how to fix that: https://coverage.readthedocs.io/en/7.2.7/subprocess.html
Is the drop in [trio/_core/_multierror.py](https://app.codecov.io/gh/python-trio/trio/pull/2665/blob/trio/_core/_multierror.py) also because of that?

The drop in [trio/_tests/test_exports.py](https://app.codecov.io/gh/python-trio/trio/pull/2665/blob/trio/_tests/test_exports.py) seems to be the test timeout on `3.12` so that's not an issue.

**Comment by A5rocks** [comment]
Wait a second, `trio/_core/_tests/test_multierror_scripts/_common.py` literally does the thing coverage.py recommends doing. It still doesn't work. What??

**Comment by A5rocks** [comment]
of *course* the thing that literally reads the file is not going to work. why did i miss that...

**Comment by A5rocks** [comment]
welp no clue why the coverage for a few more files isn't working. i give up for now.

**Comment by jakkdl** [comment]
> welp no clue why the coverage for a few more files isn't working. i give up for now.

I suppose we can just exclude `trio/_core/_tests/test_multierror_scripts/*` from coverage and leave fighting with this for some future crazy person.

**Comment by jakkdl** [comment]
Huh, there's *four* codecov checks? :o 

Anyway, it looks good now - merging~~

**Comment by A5rocks** [comment]
> Huh, there's _four_ codecov checks? :o

... weird. Eh, we can fix that eventually!

**Comment by A5rocks** [comment]
Ok, the four codecov thing was just cause this was an old PR: https://github.com/python-trio/trio/pull/2674 only has 2 checks! (as it should be)

**Pull request merged**
