### PR TITLE
Add local_address= kwarg to open_tcp_stream

### PR DESCRIPTION
**Pull request by njsmith**
Fixes gh-275

### CODE REVIEW

**Comment by oremanj** [comment]
Thanks for the detailed comment on `bind()` -- I learned something!

**Comment by ntninja** [comment]
That was way too fast for me…! :open_mouth: 

Do I see it correctly that with this API limiting a connection to `socket.AF_INET`/`socket.AF_INET6` address families during name resolution is done by passing `"0.0.0.0"`/`"::"` respectively for the `local_address=…` arg?

**Comment by njsmith** [comment]
@ntninja Currently, `open_tcp_stream` always does full name resolution, but if you pass `local_address="0.0.0.0"` then it will only skip trying to connect to the `AF_INET6` addresses and if you pass `local_address="::"` then it will skip trying to connect to the `AF_INET` addresses. Technically this is very slightly inefficient (`getaddrinfo` still has to look up both sets of addresses), but this is very minor, and in return, we get better error messages: e.g., if you accidentally try to connect to an IPv6-only host with `local_address="0.0.0.0"`, then it will fail, but the error message will tell you that there *were* IPv6 addresses it considered connecting to and if you changed your `local_address=` you might succeed.

**Comment by ntninja** [comment]
Ok, thanks! I don't have any strong feelings on this, just wanted to know for sure!

**Pull request merged**
