### PR TITLE
Add note about cancellation and memory channels

### PR DESCRIPTION
**Pull request by decentral1se**
Ripped from the gitter channel. Might help.

### CODE REVIEW

**Comment by decentral1se** [comment]
Ah, don't think that coverage issue relates to my change then.

**Comment by tjstum** [comment]
This looks good to me, and I agree with your assessment about coverage.

Do we want to mention this in the reference documentation for `SendChannel` and `ReceiveChannel` (i.e. mention it in `send` and `receive`)?
We also might want a similar mention about `send` being cancelled at _just_ the right moment causing the channel to be empty but no one's `receive` unblocking (unless I am misunderstanding the issue here)

**Comment by njsmith** [comment]
Thanks, and sorry for the delayed review!

I don't think we want to make this kind of atomicity part of the generic `SendChannel`/`ReceiveChannel` contract, because those are also useful for things like TCP-stream-plus-framing, where atomicity would be extremely difficult.

**Comment by decentral1se** [comment]
Thanks!

**Pull request merged**
