### PR TITLE
Enable ruff's `flake8-commas` rule

### PR DESCRIPTION
**Pull request by CoolCat467**
In this pull request, we enable ruff's `flake8-commas` rule and handle all the reformatting black does because of this.

~No functional changes~ Had to update `gen_exports` to run black a 2nd time, if/when this is merged it will probably need to be added to the purely formatting commits thing jakkdl was talking about a while ago.

### CODE REVIEW

**Comment by jakkdl** [comment]
> In this pull request, we enable ruff's `flake8-commas` rule and handle all the reformatting black does because of this.
> 
> ~No functional changes~ Had to update `gen_exports` to run black a 2nd time, if/when this is merged it will probably need to be added to the purely formatting commits thing jakkdl was talking about a while ago.

#2837

**Comment by CoolCat467** [comment]
pre-commit.ci autofix

**Review by jakkdl — APPROVED** [review]

**Review by A5rocks — APPROVED** [review]
Spot-checks fine. I'm not sure how useful this will be, though forcing `noqa` and `type: ignores` onto lines with only that argument is actually useful.

**Comment by jakkdl** [comment]
> Spot-checks fine. I'm not sure how useful this will be, though forcing `noqa` and `type: ignores` onto lines with only that argument is actually useful.
> 
> Though, can you put this in a blame-ignore file?

it's also generally useful for minimizing diffs when only changing a single argument.

And yes, this should be in blame-ignore. If you wanna be strictly correct you can reshuffle the commits so there's one that is pure refactoring, and one that contains the functional changes to `gen_exports`. This can for example be done with something like (untested, and might depend on the state of your local repo)
```
git reset origin/main
git stash push --patch src/trio/_tools/gen_exports.py
[interactively only stash the functional changes]
git commit -am [...]
git stash pop
git commit -am [...]
```

after some brief testing it appears it's possible to add the hash to `.git-blame-ignore-revs` and not have it change if the PR is merged with a merge commit, in which case you can also do that in the second commit (or in a third).

If you mess up, there's `git reflog`, or pulling from the remote branch. If you don't manage to work it out lmk and I can do it :)

**Review by A5rocks — APPROVED** [review]

**Comment by jakkdl** [comment]
2024-08-31T13:03:13,100427169+02:00
https://github.com/python-trio/trio/blame/main/docs/source/conf.py
whoop whoop!

**Pull request merged**
