### PR TITLE
Addresses #1958: Move code that handles job into its own method

### PR DESCRIPTION
**Pull request by cslecrone**
Attempting to address #1958 by moving the code that handles jobs into its own method. This is my first contribution, so let me know if I need to do anything differently. Thanks!

### CODE REVIEW

**Comment by njsmith** [comment]
That's weird... it looks like Travis just... doesn't know about this PR, for some reason: https://travis-ci.com/github/python-trio/trio/pull_requests

Might be related to their limited OSS credits, but OTOH they are currently building the latest commit to the master branch, so... idk. We should get off of Travis (see #1785). For right now, I'll try closing/reopening and see if that's enough to tickle Travis into doing something.

**Comment by njsmith** [comment]
https://travis-ci.com/github/python-trio/trio/pull_requests

**Comment by njsmith** [comment]
Looks like travis is running now, so fingers crossed it works out :crossed_fingers: 

Anyway, the code change looks good! Could you add a comment explaining why `_handle_job` is separated into its own method?

**Comment by cslecrone** [comment]
Of course! Added one just now.

**Comment by richardsheridan** [comment]
In https://github.com/python-trio/trio/issues/1864#issuecomment-759113248 @oremanj expressed concerns about injecting extra function frames into frequently-called codepaths, preferring `del` everywhere in that case. I wonder if he would raise the some objection here given the opportunity? He ran into the same issue while implementing #1652 (https://github.com/python-trio/trio/pull/1652/files#r486806508) and bugfixed it by using `del result`, @njsmith noted in #1958.

**Comment by njsmith** [comment]
> In #1864 (comment) @oremanj expressed concerns about injecting extra function frames into frequently-called codepaths, preferring del everywhere in that case. I wonder if he would raise the some objection here given the opportunity?

Ah, interesting point, I didn't think of that! Thanks for making the connection.

Looking at it, I think this case is different: there he was talking about the core scheduling loop, which runs on every checkpoint, so it's like... the hottest code in trio by a long way. Here, we're talking about one extra frame per job assigned to a worker thread. Passing a job into a worker thread is pretty cheap, but it's still much *much* more expensive than pushing a call frame. Concretely, the measurements in https://github.com/python-trio/trio/pull/1545 are in tens of µs, while on my same laptop a trivial Python function call is in tens of ns, so ~3 orders of magnitude faster. So in this case I don't think it's a concern.

**Comment by oremanj** [comment]
I’m not worried about the overhead in this case, though I agree it’s good to think about in general!

**Pull request merged**
