### PR TITLE
Modernize codebase to python 3.7+ standard

### PR DESCRIPTION
**Pull request by harahu**
This PR is the result of a one-off run of `pyupgrade` on the trio code base.

For future reference, this was done by running the following command from the project root:

```sh
find . -name '*.py' -exec pyupgrade --py3-only --py37-plus {} +
```

I also ran black in preview mode (`black --preview`), which mainly results in string cleanup.

### CODE REVIEW

**Comment by harahu** [comment]
I hope this can be merged. I'm realizing that  it might seem daunting to review this, given the diff size, but the tools I've used are conservative w.r.t modifying behavior, so the changes should be relatively safe.

**Comment by pquentin** [comment]
@Fuyukai as a member, you get to approve and merge this if you like it!

**Comment by harahu** [comment]
I hope it can be merged. I want to make further changes on top of this.

**Review by pquentin — CHANGES_REQUESTED** [review]
Thanks! Can you please exclude notes-to-self?

**Comment by harahu** [comment]
> Thanks! Can you please exclude notes-to-self?

@pquentin I've done so now. I get one failing test suite, but I think it might be a case of test flakiness? What is your take?

**Comment by pquentin** [comment]
Not sure what's going on sorry. I've relaunched the Ubuntu 3.7 tests a few times and it appears to fail consistently which is concerning.

**Comment by harahu** [comment]
> Not sure what's going on sorry. I've relaunched the Ubuntu 3.7 tests a few times and it appears to fail consistently which is concerning.

I'll see if I can figure out what is going on. Perhaps later today.

**Comment by pquentin** [comment]
I can confirm that the Ubuntu 3.7 failures are not specific to this pull request.

**Comment by harahu** [comment]
> I can confirm that the Ubuntu 3.7 failures are not specific to this pull request.

Thanks @pquentin! Was scratching my head over this one.

**Comment by pquentin** [comment]
Would you mind opening a pull request that skips this test?  I can only imagine that a fix in more recent versions was not backported there. I don't want to invest time in debugging this, especially when Python 3.7 won't be supported anymore in 7 months, and this is blocking us.

**Review by pquentin — APPROVED** [review]
LGTM! THanks for your patience.

**Comment by pquentin** [comment]
(I'll let you click on the green merge button yourself!)

**Pull request merged**
