### PR TITLE
Let the Nursery context-manage itself

### PR DESCRIPTION
**Pull request by smurfix**
I was curious whether the commented-out NurseryManager class would actually work, so I turned it on ;-)
I had to insert one conditional because of an impedance mismatch between context managing and cancel handling. All tests pass.

On second thought (second patch), a Nursery can be its own context manager. This can be improved further (third patch) by deferring the initialization to `__aenter__()`, noting that a Nursery is never used outside of a context manager.

This change speeds up the full test run by a bit more than 1% on my system (tested with 3.5 and 3.6).

### CODE REVIEW

**Comment by njsmith** [comment]
I should note here: the nursery implementation is going to get majorly revisited in 0.3.0 (#136), so I've been putting this off to look at as part of that.

**Comment by njsmith** [comment]
First pass of simplified nurseries is in #375.

Do you remember why you had to add the `if isinstance(exc, Cancelled): return True` bit to your `Nursery.__aexit__` method? I don't see how it can be correct (doesn't it make nurseries swallow all `Cancelled` exceptions?), but I assume you ran into trouble without it...

**Comment by smurfix** [comment]
I'll test my code with the current master branch and report back.

**Comment by njsmith** [comment]
Thanks!

**Comment by kyrias** [comment]
Any updates on this? :)

**Comment by smurfix** [comment]
I'll have a look soon(ish).

**Comment by njsmith** [comment]
We should probably stop using `@asynccontextmanager` in the nursery implementation (#229, #393). But this branch is way out of date, discussion has stalled, and I think it goes a bit to far (I like that the actual `Nursery` object is only returned from `__aenter__`, not from `open_nursery`). I'm going to close this for now, and we can always re-open it or steal bits from it later if we want to.

**Pull request closed without merging**
