### PR TITLE
Fix typo in doc

### PR DESCRIPTION
**Pull request by hjbyt**

### CODE REVIEW

**Comment by sorcio** [comment]
@hjbyt I don't have any strong opinion nor authority in the matter, but I think maybe it's better to use branches in your own fork, rather than creating them in the main repo. Or possibly deleting them? I noticed there is a another branch with what looks like the same typo fix, and maybe you want to delete it.

**Comment by hjbyt** [comment]
Sorry i'm a noob w.r.t. contibuting in github.
Would you mind deleting that other branch (hjbyt-fix-type-fairness)? I rather not do it mightself, don't wanna mess something up.

**Comment by smurfix** [comment]
It's easy, just `git push origin :hjbyt-fix-type-fairness`. Mind the colon.
@njsmith does like to keep the main repo clean; the only two branches that should be in there are "master" and "release".

It's more a question of personal style than of being a noob. ;-)

**Comment by hjbyt** [comment]
Yeah, though i didn't mean to create a branch here. I didn't even clone the repo locally yet. I simply did "Edit on Github" from the docs page, made the change, and created a PR. The first time i did a PR (https://github.com/python-trio/trio/pull/525) it was through a fork. But this time since i got access to the repo, Github apparently defaulted to creating a branch here (my bad, should have been more careful).

**Comment by njsmith** [comment]
Yeah, that's an annoying thing about the "edit" button!

It's not that big a deal, just we should delete it afterwards (and once the PR is merged this is perfectly safe; github creates a button prompting you to do it, and if you see that button then you know it's safe to click).

**Pull request merged**
