### PR TITLE
CI: deadsnakes/action does not support caching

### PR DESCRIPTION
**Pull request by belm0**

### CODE REVIEW

**Comment by agronholm** [comment]
How did the tests pass if this is the case?

**Comment by agronholm** [comment]
Oh, it was just a warning.

**Comment by belm0** [comment]
> How did the tests pass if this is the case?

the gitub action only emits a warning

```
Warning: Unexpected input(s) 'cache', 'cache-dependency-path', valid inputs are ['python-version']
```

**Review by agronholm — APPROVED** [review]
Simple enough.

**Comment by belm0** [comment]
anyway I confirmed caching in the working case:

```
Run actions/setup-python@v2
Successfully setup CPython (3.7.9)
Received 20507446 of 20507446 (100.0%), 43.5 MBs/sec
Cache Size: ~20 MB (20507446 B)
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/9b6092e3-6452-4d32-afc[8](https://github.com/python-trio/trio/runs/6056947531?check_suite_focus=true#step:3:8)-27e581f1d[9](https://github.com/python-trio/trio/runs/6056947531?check_suite_focus=true#step:3:9)a9/cache.tgz -P -C D:/a/trio/trio
Cache restored successfully
Cache restored from key: setup-python-Windows-python-3.7.9-pip-ab9271867864e72640[11](https://github.com/python-trio/trio/runs/6056947531?check_suite_focus=true#step:3:11)8f[12](https://github.com/python-trio/trio/runs/6056947531?check_suite_focus=true#step:3:12)d4b69682bed39d4911d19425e772d87c837cd300
```

**Pull request merged**
