### PR TITLE
Cython Workaround

### PR DESCRIPTION
**Pull request by CoolCat467**
This pull request partially completes changes that were noted in #2908.

Either added on to this pull request or in another pull request, we still need to make sure to test that cython will continue working and not find these sorts of issues after they are already a problem.

Excerpt from original comment in #2908:
>But it would be good to also run a test for this in CI. We do have a test for the interpreter's built-in C coroutines (`test_async_function_implemented_in_C`) and I [njsmith] originally assumed that would be enough, but obviously it wasn't, so I guess we need to do the legwork to install cython in CI and build a tiny Cython module.

### CODE REVIEW

**Review by A5rocks — APPROVED** [review]
Looks good, I think actually doing the CI work can be done later (just repurpose the already made issue).

**Comment by Zac-HD** [comment]
I'd be OK with shipping this as a fix for the current problem, but I'm also keen to get some regression tests into our CI so we can tell that it's effective and notice if it breaks later.  Maybe @jakkdl can help out?

**Comment by jakkdl** [comment]
> I'd be OK with shipping this as a fix for the current problem, but I'm also keen to get some regression tests into our CI so we can tell that it's effective and notice if it breaks later. Maybe @jakkdl can help out?

I'll take a look at it, seems quite doable. But agree on merging this and getting CI setup in a later PR.

**Review by jakkdl — APPROVED** [review]

**Comment by CoolCat467** [comment]
Ok, with two approvals I am going to merge this.

**Pull request merged**
