### PR TITLE
Make sure the index is synced before diff-index

### PR DESCRIPTION
**Pull request by A5rocks**
This should fix autodeps once and for all. Hopefully!

Seems to work here: https://github.com/python-trio/trio/actions/runs/4899533479/jobs/8749560235#step:6:57

### CODE REVIEW

**Review by richardsheridan — COMMENTED** [review]
Good sleuthing! Does this mean that the `-a` of the `git commit` is redundant now? Also, what do you think of just checking the return code of `git commit -a`?

**Comment by A5rocks** [comment]
Done and it still works: https://github.com/python-trio/trio/actions/runs/4936843958/jobs/8824875611#step:6:55

**Comment by richardsheridan** [comment]
Amazing, thanks!  It's much simpler to follow this way.

**Comment by Sxderp** [comment]
https://github.com/python-trio/trio/blob/d0d8d618157c5b9270f7f012ba809118cfc6ce9f/.github/workflows/autodeps.yml#L47

Should be "git commit" no?

**Comment by richardsheridan** [comment]
Yes, could you make a fix PR that we could merge?

**Comment by A5rocks** [comment]
Ahh oops, well no wonder it errored -> no changes :S

**Pull request merged**
