### PR TITLE
Add checks for if instruments exist before running instrument functions.

### PR DESCRIPTION
**Pull request by Fuyukai**
This provides a small speed-up.

Microbenchmark script:

```py
import time

import trio


async def main():
    q = trio.Queue(0)

    async def i1():
        await q.put("123")

    async def i2():
        i = await q.get()

    start = time.time()
    print("Start time", start)
    async with trio.open_nursery() as n:
        for x in range(0, 5_000):
            n.start_soon(i1)
            n.start_soon(i2)
            if x % 500 == 0:
                await trio.sleep(0)

    end = time.time()
    print("End time", end)
    print("Elapsed", end - start)


trio.run(main)
```

Before:
```
Start time 1535036274.015487
End time 1535036274.5630355
Elapsed 0.5475485324859619
```

After:
```
Start time 1535036229.3229249
End time 1535036229.8288205
Elapsed 0.5058956146240234
```

I generally got a ~40-50ms speedup with this change.

### CODE REVIEW

**Comment by njsmith** [comment]
eh, in the long run I think we should try to approach these things systematically based on benchmarks and bottlenecks people experience in real life (#604), but this particular change is so trivial and harmless that sure, why not.

**Comment by Fuyukai** [comment]
I actually discovered this by a profile - a suspicious amount of time was being spent inside instrument() so I added these guards and they seemed to reduce it by a bit.

**Comment by njsmith** [comment]
Oh interesting, what were you profiling?

**Comment by njsmith** [comment]
Neat. BTW, if it's possible to convert your bot code into a benchmark (like literally: take the existing code and wrap a harness around it), that could be a good way to start at #604 ... the more quirky real-world stuff is in a benchmark, the better it is for guiding these kinds of decisions :-).

**Pull request merged**
