### PR TITLE
Save an s

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by oremanj** [comment]
LGTM - feel free to click the button once CI passes.

**Comment by pquentin** [comment]
The FreeBSD build failed when downloading Ubuntu files. Cycling.

**Comment by pquentin** [comment]
It's not a big deal, but please try to open branches in your personal fork: one reason is that it avoids doubling the number of tests that need to pass

**Comment by altendky** [comment]
I'm not used to having main repo access... I'll try to keep that in mind.

**Pull request merged**
