### PR TITLE
Run the iteration for glob, rgblob and iterdir in a thread

### PR DESCRIPTION
**Pull request by vxgmichel**
Fix issue #1308.

I wrote the simplest fix, just to get things started.

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks! Can you please add a small comment to explain that it's an optimization?

**Comment by vxgmichel** [comment]
@pquentin Sure! It's not an optimization though, it's a bug fix: file system calls in pathlib are actually performed during the iteration which means the iteration itself has to run in a thread.

**Comment by pquentin** [comment]
Thanks!

**Comment by pquentin** [comment]
Yay, welcome!

Can you please open a new PR to add a newsfragment explaining the change? See https://trio.readthedocs.io/en/stable/contributing.html#release-notes. Sorry I forgot about that *again*.

**Pull request merged**
