### PR TITLE
Try Azure pipelines

### PR DESCRIPTION
**Pull request by njsmith**
Like #826, but using a branch fork to stress Travis/Appveyor less.
Will it work? Let's find out!

### CODE REVIEW

**Comment by njsmith** [comment]
Twitter thread about how pip is bizarrely slow on Azure: https://twitter.com/vorpalsmith/status/1078546817409662976

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by njsmith** [comment]
@kaylangan Hi Kayla! This got somewhat derailed by the discovery that for some reason the MS-hosted Windows boxes in Azure Pipelines are inexplicably, unreasonably slow at doing basic test environment setup: https://github.com/njsmith/bench-pip-windows-ci

I [tweeted](https://twitter.com/vorpalsmith/status/1078546817409662976) about this, and apparently I'm [not alone](https://twitter.com/scopatz/status/1078618401151610880) ([another complaint](https://twitter.com/anthonypjshaw/status/1078552703851126784)). Two different MS employees – Steve Dower and [David Aronchick](https://twitter.com/aronchick/status/1078808305986953216) – asked me for more details, so I assume they've passed something on internally, but I don't know what or to who.

Of course this was in the middle of the holidays so I doubt much has happened yet, but if you do have any updates on what's going on here, that would be super appreciated!

**Comment by njsmith** [comment]
Closing in favor of #841, which uses azure-pipelines for just one weird test to try it out.

@kaylangan You might also be interested in this issue: https://github.com/MicrosoftDocs/vsts-docs/issues/2939 – I originally started using azure pipelines here because I needed to test in a container and I thought pipelines would be good for that because of its first-class `container:` support, but that turned out to be unusable for us.

**Comment by njsmith** [comment]
Re-opening to experiment some more

**Comment by njsmith** [comment]
Status:

* Apparently Azure's pre-built Linux Pythons are all built against openssl v1.1.1. I guess this must be related to why all our Linux tests are hanging in the ssl tests. But I don't really understand it. For py35, openssl v1.1.1 is probably not possible to fix, b/c the new TLS v1.3 APIs aren't wrapped at all, so you're just stuck with the default behavior. But for py36 and py37, I would have thought it should work... the same build does pass on the `py37_latest_ubuntu` container, which also has py37 + openssl v1.1.1. No idea why the MS-built version acts different.

* macOS tests seem to be working fine

* Windows tests are failing for some actual reason – the tests that spawn a child ipython are failing because they try to do `import _common` and it fails.

* No flag support in `ci/ci.sh`... and tons of code duplication with `ci/travis.sh`

The Linux support thing is a mess. Fortunately, Travis is pretty good at Linux, so it's not a high priority at all. Probably the initial question is just whether we can make things faster by moving Windows to AP. If we do decide we want to consolidate everything onto AP, then for Linux it might even make sense to set up a nightly build that just generates a bunch of pre-built docker images with all the configurations we want to test against, that we can run our actual test builds in. But again, not important right now...

**Comment by njsmith** [comment]
Apparently the strange Windows failure only affects 3.5.

**Comment by njsmith** [comment]
And apparently in the failing Windows tests, we're setting PYTHONPATH, apparently correctly, but it's not actually affecting `sys.path` in the child... mysterious.

**Comment by njsmith** [comment]
@zooba Sorry to bother you, but I'm seeing something very odd here and I'm stumped. Do you have any idea why on Python 3.5 installed from nuget (but not other versions on nuget, and not 3.5 when installed not-from-nuget!), the PYTHONPATH envvar would be ignored? [Notice here](https://dev.azure.com/python-trio/trio/_build/results?buildId=47&view=logs&jobId=664b18cd-4bf7-594d-23bc-48451a51c56b&taskId=e3961842-a598-59ab-eeac-32ea4b0d6853&lineStart=1313&lineEnd=1317&colStart=1&colEnd=1), lines 1313-1315:

```
2019-01-24T23:03:56.2459614Z inside simple_excepthook.py, sys.path is ['', 'd:\\a\\1\\s\\pyinstall\\pythonx86\\tools\\python35.zip', 'd:\\a\\1\\s\\pyinstall\\pythonx86\\tools\\DLLs', 'd:\\a\\1\\s\\pyinstall\\pythonx86\\tools\\lib', 'd:\\a\\1\\s\\pyinstall\\pythonx86\\tools', 'd:\\a\\1\\s\\pyinstall\\pythonx86\\tools\\lib\\site-packages', 'd:\\a\\1\\s\\pyinstall\\pythonx86\\tools\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\VssAdministrator\\.ipython']
2019-01-24T23:03:56.2459792Z 
2019-01-24T23:03:56.2459963Z inside simple_excepthook.py, PYTHONPATH is D:\a\1\s\pyinstall\pythonx86\tools\lib\site-packages\trio\_core\tests\test_multierror_scripts;D:\a\1\s\pyinstall\pythonx86\tools\lib\site-packages
```

So `D:\a\1\s\pyinstall\pythonx86\tools\lib\site-packages\trio\_core\tests\test_multierror_scripts` is in` PYTHONPATH`, but not on `sys.path`...

**Comment by njsmith** [comment]
Looked at this a little more closely... it's actually even more messy than I realized, because it's apparently not *all* the tests that spawn a subprocess with custom PYTHONPATH that are failing, it's just the ones that involve ipython as well. Wheee!

**Comment by zooba** [comment]
It looks like the Nuget package for 3.5.4 includes the old `applocal = True` option (which became `._pth` files in 3.6 but was removed from the Nuget packages). That option implies `-E`, and so environment variables are ignored.

I don't recall now why I thought it was a good idea at the time :) It was definitely before I was able to fix some of the layout detection issues, so it may have been the way to prevent a regular Python 3.5 install from interfering.

Deleting the `pyvenv.cfg` file in `sys.prefix` should be enough.

**Comment by njsmith** [comment]
@zooba Looks like that worked nicely, thanks!

**Comment by njsmith** [comment]
This is looking pretty good... this now has azure and travis using a single shared script. The azure build is checking all our Windows + macOS configurations in ~2 minutes wall time. Appveyor OTOH needs ~10 minutes to run Windows (and uses a totally different CI script we have to maintain just for it), and Travis varies but in the last build I looked at it spent ~10 minutes running macOS tests at the very end, and for some reason they didn't start until after everything else was finished + were run in serial. So switching Windows + macOS over to azure pipelines looks like a significant win.

I figure we can merge this, and let both sets of builds run in parallel for a bit to shake out any issues before we turn off appveyor and the travis macOS builds.

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
