### PR TITLE
small fail_at() doc fix

### PR DESCRIPTION
**Pull request by sorcio**

### CODE REVIEW

**Comment by sorcio** [comment]
Ignore the CI failure, it's #508 again.

```
Collecting sortedcontainers (from trio==0.4.0+dev)
  1 location(s) to search for versions of sortedcontainers:
  * https://pypi.org/simple/sortedcontainers/
  Getting page https://pypi.org/simple/sortedcontainers/
  Looking up "https://pypi.org/simple/sortedcontainers/" in the cache
  Current age based on date: 237310
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  https://pypi.org:443 "GET /simple/sortedcontainers/ HTTP/1.1" 304 0
  Skipping page https://pypi.org/simple/sortedcontainers/ because of Content-Type: unknown
  Could not find a version that satisfies the requirement sortedcontainers (from trio==0.4.0+dev) (from versions: )
```

**Comment by njsmith** [comment]
Nice catch! We have branch protection enabled, so we can't easily merge without the CI passing, so I'm going to try to joggle jenkins into re-running...

**Comment by Fuyukai** [comment]
That didn't work either. Try 2.

**Comment by njsmith** [comment]
We gotta fix that coverage flapping in `test_highlevel_open_tcp_listeners.py` too... I'm tempted to just `# pragma: no cover` the whole function because it's a little helper that we don't care about, but it bothers me that I don't understand how that coverage result is possible.

Anyway, this change is fine of course, thank you :-). Is this really your first PR? I'll send [the invitation](https://trio.readthedocs.io/en/latest/contributing.html#joining-the-team) in a moment...

**Comment by njsmith** [comment]
> Is this really your first PR?

Oh right, of course this is because I've been delinquent in reviewing #473. Let me do that right now...

**Pull request merged**
