### PR TITLE
socket: ignore OSError during IPV6_V6ONLY-normalization

### LINKED ISSUE #164: Invalid argument exception during socket.accept on AF_INET6
minimal-ish testcase and exception: https://gist.github.com/8d647f4c8368bc318e73833474601526

If I remove the `setsockopt` call on line 192, the testcase works as expected.

Is this a bug, or am I not creating an IPv6 socket correctly?

### PR DESCRIPTION
**Pull request by buhman**
~This doesn't appear to work with all types of AF_INET6 sockets--it is likely better to have the caller handle this instead.~ I've now changed this to ignore OSError instead based on your feedback in #164.

Fixes #164.

### CODE REVIEW

**Comment by njsmith** [comment]
Thanks for the patch! Codecov failure is annoyingly caused by #140, nothing to do with you. And having pondered https://github.com/python-trio/trio/issues/164#issuecomment-302622899 and slept on it, I think I'm going to go ahead and merge this, and worry about fixing it up again at the next level up :-)

**Comment by njsmith** [comment]
Oh wait, of course I had the tab open from yesterday and as soon as I hit post it updated to show I was replying to the old different version.

Oh well, this one is fine too :-). The immediate goal is to get this unbroken, and the details can be sorted out when the higher-level code arrives.

**Comment by njsmith** [comment]
Oh, right, now the codecov failure is real though – there's no test where the `setsockopt` fails. Is that something you can easily add? (Probably a good idea no matter which approach we take...)

**Comment by buhman** [comment]
> there's no test where the setsockopt fails. Is that something you can easily add? 

Sure thing.

**Comment by buhman** [comment]
@njsmith :+1:

**Comment by njsmith** [comment]
Awesome, thanks!

**Comment by njsmith** [comment]
Want a commit bit? You can join in as much or little as you want, but my policy is to offer one to everyone who contributes a patch :-)

**Pull request merged**
