### PR TITLE
📝  Add small description of call stack in tutorial

### PR DESCRIPTION
**Pull request by tiangolo**
:memo: Add small description of "call stack" in tutorial.

---

Thanks for building Trio! I love how beginner-friendly the tutorial is, it makes me feel that I'm learning and that I'm welcome.

In the same spirit, I realized the first mention of "call stack" doesn't have an explanation about what it is.

I think it might not be obvious, and given there's a great explanation above about async context managers, I thought this could be relevant too.

### CODE REVIEW

**Comment by tiangolo** [comment]
It seems there's an issue with CI itself (independent of this PR), I'm fixing that CI problem is this other PR: https://github.com/python-trio/trio/pull/2037

**Comment by tiangolo** [comment]
Thanks to @pquentin for merging the CI fix mentioned above! That was super fast. 🙇 🚀 

---

I just rebased this PR, so now CI runs and it can be reviewed. 🎉

**Comment by pquentin** [comment]
Hey @tiangolo, I have many things to thank you for 😄 Your interest in Trio, #2037 that fixed our CI, your help with the documentation, your kind words, FastAPI (I'm a happy user), your work on spaCy and the fact that you're taking two days a week to work on open source.

Please let us know if you're building something with Trio, we'd be happy to help!

---

You're totally right that the call stack should not be required knowledge. And I'm amazed that you were able to explain what it was usefully in a few words. However, looking at the resulting docs at https://trio--2036.org.readthedocs.build/en/2036/tutorial.html#task-switching-illustrated, I wonder: should we just remove the words "call stack" altogether?

My proposal:

> The secret is that `trio.run()` and `trio.sleep()` work together to make it happen: `trio.sleep()` has access to some special magic that lets it pause itself, so it sends a note to `trio.run()` requesting to be woken again after 1 second, and then suspends the task.

**Review by pquentin — APPROVED** [review]
Thank you!

**Comment by tiangolo** [comment]
Thank you! 😊 

I hadn't had the chance to learn Trio, although I keep hearing great things about it. Learning it was in my pending backlog for a while. 🤓 

There's currently an ongoing PR to Starlette to use AnyIO, and that way, support Trio: https://github.com/encode/starlette/pull/1157

I know Tom wanted that, and I remember he has praised Trio before (I don't remember exactly where). So, I feel that's gonna arrive there soon. This would mean that it would arrive at FastAPI soon too. ✨ 

...and that raises the priority for me to learn Trio even more. 😅 

I also want/need to add some utilities and documentation about how to simply call blocking code from async, and async from blocking. And I want to make sure I'm having all that into account, to try and make it in a way that is compatible with everything in the future too.

---

About the suggestion, that's even better and much more simple! Thanks! 🤓 🚀 

And thanks for merging! 🎉

**Pull request merged**
