### PR TITLE
timeout coverage/pytest with sigint to help debug CI timeout issues

### PR DESCRIPTION
**Pull request by jakkdl**
didn't find any dead simple ways of doing this within pytest. I hope this works on other platforms

### CODE REVIEW

**Comment by jakkdl** [comment]
wait hmm, the timeouts happening on `Ubuntu (pypy-3.9)` and `Ubuntu (pypy-3.10)` are some very different type of timeout than the CI being mad ... I think??
It's at least talking about some 1min timeout being triggered

**Comment by jakkdl** [comment]
Okay, actually digging into the traces I now realize this isn't about the CI killing at all - this seems to be Trio itself giving up in the main event loop. And it's not any particular test triggering it.

Manually going back and checking runs, the oldest I can find is https://github.com/python-trio/trio/actions/runs/6442036631/job/17492440655 .... in a PR that is modifying thread behaviour. So it's possible that #2392 has some subtle bugs, and should maybe be reverted for now?

**Comment by A5rocks** [comment]
TBH this PR isn't needed for an immediate issue anymore and does complicate CI a bit. Do you think it's still worth pursuing?

**Comment by jakkdl** [comment]
not especially. I do like the extra refactoring I did of pulling apart the previously huge and tricky-to-parse line though.

**Comment by jakkdl** [comment]
although: https://github.com/python-trio/trio/actions/runs/6641043117/job/18042685943?pr=2820

weirdly enough it displays as having passed despite being canceled???

**Comment by A5rocks** [comment]
Yeah I'm not sure what's up with that CI pass :(

I'm going to hope it's gone away. And we've cleaned up the line a bit more. Feel free to open a new PR (or reopen this and fix conflicts) if you still think it would benefit from more refactoring!

**Pull request closed without merging**
