### PR TITLE
Run tests on FreeBSD

### PR DESCRIPTION
**Pull request by thedrow**
Let's see how magnificently this fails :)

### CODE REVIEW

**Comment by thedrow** [comment]
I don't see the build being triggered.

**Comment by pquentin** [comment]
I think tou need a `.cirrus.yml` file? Note that you can test this in your own fork if you want to.

**Comment by thedrow** [comment]
Yeh I forgot to add the file.

**Comment by njsmith** [comment]
Mysterious failure. I guess the first thing I would try is running `pwd` and `ls` just to get more context about what's happening. But I suspect you might need to run `pkg install -y bash`

**Comment by thedrow** [comment]
Seems like the FreeBSD environment isn't properly configured or something.
It doesn't have bash.

I'll investigate.

**Comment by njsmith** [comment]
And now cirrus-ci is just... not running at all. That's not very confidence-inspiring :-/

**Comment by thedrow** [comment]
> And now cirrus-ci is just... not running at all. That's not very confidence-inspiring :-/

Which is exactly why I wanted to try it before recommending to anyone else.
This project is a good candidate for it.

**Comment by njsmith** [comment]
Well, I opened an issue here; let's see if they respond: https://github.com/cirruslabs/cirrus-ci-docs/issues/352

**Comment by njsmith** [comment]
Initial observation: so far Cirrus CI has been incredibly slow at starting jobs... on [this run](https://cirrus-ci.com/task/5199364903927808) it took ~8 minutes before it even started cloning our repo. The rest of our CI runs 22 jobs, and was completely finished in <6 minutes. (And even that's somewhat unoptimized... it would be faster if we moved more of the travis jobs to azure pipelines.)

Also, the Cirrus CI job status page looks very fancy with animations and stuff, but it keeps showing me stale information, and I have to repeatedly hit "Reload" to see what's actually happening.

**Comment by njsmith** [comment]
The tests are actually running now. There seem to be several failures and also several deadlocks that will need investigating before we could enable this for real: https://cirrus-ci.com/task/4891573119090688

**Comment by thedrow** [comment]
It's good to know that Cirrus is slow.
I wanted to enable it on py-amqp as well.
The real question is, do we want to support FreeBSD?

**Comment by njsmith** [comment]
There are other things that are higher priorities for me than FreeBSD support, so I probably won't work on it myself anytime soon, but if people care enough to do the work then I'm happy to merge patches. I doubt it will take many changes.

**Comment by njsmith** [comment]
Closing this for now, since it's stalled out. We're still in favor of doing something like this in principle, but no point in keeping this in the list of open PRs if no one's working on it :-). We'll leave #1118 open for general discussion of BSD support.

**Comment by thedrow** [comment]
I'll probably refocus my efforts on this once we'll need it in Celery.

**Pull request closed without merging**
