### PR TITLE
Drop Python 3.5

### LINKED ISSUE #75: Dropping python 3.5 support?
Advantages of going to 3.6+:

* f strings
* the `__aiter__` mess goes away
* native async generators → slightly nicer tracebacks
* idempotent call_soon becomes guaranteed FIFO (not sure anyone cares but hey)

Disadvantages:
* 3.6 final won't be in any ubuntu release until 17.04
* there's no pypy 3.6 (but pypy 3.5 does have f-string support at least)
* some complications on RTD

My feeling is that it's not quite time to drop 3.5 support, but it wouldn't be too bad to start allowing f-strings in the medium term. And beyond that pypy becomes the gating factor.

### PR DESCRIPTION
**Pull request by pquentin**
Closes #75 

I'll need to write newsfragments for 1/ the actual removal 2/ the call_soon FIFO ordering guarantee.

@oremanj Can `test_abc_generics` go away with Python 3.5 or is it still useful?

### CODE REVIEW

**Comment by pquentin** [comment]
Coverage is pointing more places where I need to change things. Unfortunately I can't put my PR in draft mode now. I'll request reviews when this is ready.

**Comment by pquentin** [comment]
Closing for now as I'm not sure I'll be able to continue this, but keeping the branch alive in case someone wants to continue the work started here.

**Comment by wgwz** [comment]
@pquentin do you have a list of things that need to be done for completion?

**Comment by pquentin** [comment]
@wgwz Thanks for stepping up! There's nothing specific left, we just need to figure out why the tests don't pass (probably due to one of the last commits), and then make sure the coverage does not drop (which is a bit tricky since it's flaky and Windows coverage is currently broken).

**Comment by pquentin** [comment]
I realized I forgot to close, doing this now so that the work can continue in another pull request.

**Comment by njsmith** [comment]
It wouldn't be a terrible idea to stick in a deprecation warning for a
release, anyway – just check if we're on 3.5 at import, and issue a warning
if so. Do you have time for a smaller PR like that?

**Comment by pquentin** [comment]
Yes, that would be a good first step.

**Pull request closed without merging**
