### PR TITLE
Add back cffi on install_requires

### PR DESCRIPTION
**Pull request by pquentin**
The wheel bug was fixed in 2017 by setuptools. Indeed, the METADATA is correct now.

https://github.com/pypa/wheel/issues/181

### CODE REVIEW

**Comment by njsmith** [comment]
This isn't quite right, one way or another – we have a workaround too, a bit further down the file, where we use this weird old extras syntax instead that generates the same wheel metadata. So we definitely don't need to do it twice :-) it's true that the workaround isn't doing much for us these days though...

**Comment by pquentin** [comment]
Thanks! I added a commit to fix that.

I checked that the wheel METADATA file continues to contain this:

```
Requires-Dist: cffi (>=1.12) ; os_name == "nt"
Requires-Dist: contextvars (>=2.1) ; python_version < "3.7"
```

And that trio.egg-info/requires.txt in the sdist still contains this:

```
[:os_name == "nt"]
cffi>=1.12

[:python_version < "3.7"]
contextvars>=2.1
```

So as long as the person releasing trio is not using anything too ancient, the result will be exactly the same as before.

**Comment by pquentin** [comment]
@njsmith Can you please take another look?

**Comment by pquentin** [comment]
Thank you!

**Pull request merged**
