### PR TITLE
fix docstring typo in to_thread_run_sync

### PR DESCRIPTION
**Pull request by sorcio**

### CODE REVIEW

**Comment by sorcio** [comment]
I've been out of the loop too long to understand these CI errors. This is a trivial typo fix so I will just leave this here.

**Comment by pquentin** [comment]
@sorcio You've hit https://github.com/python-trio/trio/issues/1402, unfortunately. I cycled your pull request so that you get the current fix, https://github.com/python-trio/trio/pull/1405.

**Comment by pquentin** [comment]
@njsmith Somehow we ended up with a `continuous-integration/travis-ci/push` check here that is failing but is required. Do you know if it's possible to only require `continuous-integration/travis-ci/pr`?

**Comment by njsmith** [comment]
Unfortunately, no, I just get one checkbox for all the travis checks together:

image

This is a stupid edge case, where the tests we care about are passing, and it's only happening because of a temporary mess on master *and* a quirk of this PR (the branch being in the main repo instead of in a fork). I'm just going to disable that checkbox momentarily and merge this so we can move on :-)

**Comment by njsmith** [comment]
OK, merged and the CI requirement is re-enabled.

...Also, I was wrong, this PR *is* from a fork. Weird. Maybe @sorcio has travis running on his fork or something? Anyway I'm not going to worry about it unless it happens again.

**Comment by sorcio** [comment]
Oh. I know what happened. I'm used to have my fork as `origin` and the original as `upstream`, but my remotes were set up in a different way. So I mindlessly had pushed to origin to make a PR from my fork, but instead made a branch here. Therefore I deleted the branch (didn't open a PR) and after a few minutes I pushed a branch *with the same name* to my fork (and made this PR from that). Apparently this was enough to confuse Travis, and most of us. My mistake! Sorry, it was lot of work for a silly typo :)

**Pull request merged**
