### PR TITLE
Empty PR for test purposes.

### PR DESCRIPTION
**Pull request by Fuyukai**

### CODE REVIEW

**Comment by njsmith** [comment]
Well, that's annoying.

It looks like pytest-cov had a release yesterday, maybe that's the issue...

**Comment by njsmith** [comment]
So it's a regression caused by pytest-cov 2.6.0.

**Comment by njsmith** [comment]
Guess we might as well merge this to unblock things for now.

**Comment by pquentin** [comment]
Closing in favor of https://github.com/python-trio/trio/pull/647

**Pull request closed without merging**
