### PR TITLE
Sort imports

### PR DESCRIPTION
**Pull request by harahu**
Using `isort` to sort imports. In my opinion, this improves readability.

### CODE REVIEW

**Comment by jakkdl** [comment]
is there any reason this wasn't followed up on / isort isn't used in general? I'm a big fan of isort

**Comment by A5rocks** [comment]
I mean, other than isort's order breaking trio?

**Comment by Fuyukai** [comment]
isort also doesn't support the geriatric versions of Python that trio mandates support for anymore so you can't even install it unless you pin an old version.

**Comment by jakkdl** [comment]
> isort also doesn't support the geriatric versions of Python that trio mandates support for anymore so you can't even install it unless you pin an old version.

that doesn't stop us from running isort in CI - which runs on 3.8 currently.

**Comment by jakkdl** [comment]
> I mean, other than isort's order breaking trio?

you can `isort: skip` files where you have to avoid circular imports - but I like using it to enforce import formatting, sorting, pruning unused imports, etc to improve git diffs and increase readability.

**Comment by jakkdl** [comment]
Implemented in #2686

**Pull request closed without merging**
