### PR TITLE
Render long description as ReST

### PR DESCRIPTION
**Pull request by A5rocks**
Currently https://pypi.org/project/trio/ renders weirdly. I haven't tested this actually fixes it but I do believe it does.

### CODE REVIEW

**Comment by jakkdl** [comment]
I have no insight here, so unless others do feel free to merge and see if it fixes it.

**Comment by A5rocks** [comment]
Oh I can probably test this on test.pypi.org. I'll do that soon:tm:.

**Comment by A5rocks** [comment]
Looks like it works! https://test.pypi.org/project/A5rocks-trio/0.22.0/

**Comment by A5rocks** [comment]
I'm just going to merge this in cause it's proven itself on testpypi.

**Pull request merged**
