### PR TITLE
DOC: Order cancel_called after cancelled_caught

### PR DESCRIPTION
**Pull request by smurfix**
and add a note that you mostly don't want to use cancel_called

### CODE REVIEW

**Comment by njsmith** [comment]
Test failures are #432 and #433.

**Comment by njsmith** [comment]
Thanks! Looked good, but then I edited it a bit more :-). Feel free to merge if you like the result (and once the CI situation is sorted out...)

**Comment by njsmith** [comment]
For the record, CI issues are in #434.

**Comment by njsmith** [comment]
BTW, any reason in particular you're making branches in the main repo instead of your fork? I don't know that it's a problem or anything, it's just not something I've seen before...

**Comment by smurfix** [comment]
Nah, no particular reason except for history; the github feature to auto-allow others to push to your PR branch didn't exist when I started working with it.

**Comment by njsmith** [comment]
Cycling to force travis to redo the build. (I *think* I tried clicking "restart build", but it's still red for some reason... maybe "restart build" doesn't pick up the latest changes from master? Or maybe I just blanked and forgot to do it. Anyway, I know this works...)

**Comment by njsmith** [comment]
Or maybe I was getting confused between the PR build and the branch build? Well, they're re-running now anyway...

**Comment by njsmith** [comment]
Ok, so the problem is that apparently that (a) because this is a branch in the main repo, Travis is running the tests twice, once using their PR testing logic, and once using their branch testing logic, (b) some interaction between github's branch protection logic and how Travis reports commit statuses means that github won't allow this to be merged unless *both* sets of Travis tests are passing, and (c) when Travis tests a branch, it tests it directly, instead of merging it with master first (like it does for PRs).

Conclusion: this can't be merged until someone merges from master.

**Comment by njsmith** [comment]
Or, even easier, I put up a new PR (#436) to get back onto the normal workflow. Closing this in favor of that.

**Pull request closed without merging**
