### PR TITLE
trio.sleep_forever should be NoReturn

### LINKED ISSUE #3095: `sleep_forever` should be typed NoReturn
I think this would be more correct? the trio-typing stubs did this: https://github.com/python-trio/trio-typing/blob/c7d97072e630cced81cb8a7bb30c0707f1a5d235/trio-stubs/__init__.pyi#L198

### PR DESCRIPTION
**Pull request by Redoubts**
Fixes #3095

### CODE REVIEW

**Review by A5rocks — APPROVED** [review]
It's a shame we have to use type ignores but this makes sense to me!

**Comment by TeamSpen210** [comment]
Well, actually mypy is correct. If someone did `trio.lowlevel.reschedule()`, `sleep_forever()` could succeed. That's totally incorrect to do of course. We could just add a `raise TrioInternalError("Should never have been rescheduled!")` after the `await`, which will quiet the type error and make sure you can't do that any more.

**Review by CoolCat467 — APPROVED** [review]
Looks great

**Comment by richardsheridan** [comment]
The docstring for this function should also mention that it will raise `RuntimeError` if manually rescheduled.

**Pull request merged**
