### PR TITLE
Just delay `select.epoll` to fix import after gevent monkey patching

### PR DESCRIPTION
**Pull request by A5rocks**
This seems to work:
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.patch_all()
True
>>> import trio
>>> exit()
```

Fixes: https://github.com/python-trio/trio/issues/2848

... While trio still doesn't work under gevent, I think not erroring when importing is a good property to have.

### CODE REVIEW

**Comment by A5rocks** [comment]
cc @jeongilpark could you see if this works for you? I'm not sure if you're actually ending up using trio. (if you do, maybe we should do a better solution, like... I don't know, maybe gevent stuffs old attributes somewhere? or... idk this level of trio very well.)

**Comment by jakkdl** [comment]
> @jakkdl @CoolCat467 - is this issue and the one specifically listed below resolved now?
> 
> [gevent/gevent#2008](https://github.com/gevent/gevent/issues/2008)

no? I don't see any reason why they've would've been fixed with no changes to any code.

**Review by CoolCat467 — APPROVED** [review]
Seems simple enough, while obviously not fixing the underlying issue I think not crashing on import is important.

**Comment by TeamSpen210** [comment]
Might be a good idea to add a comment as to why we're using a lambda here. Otherwise someone coming along in the future might "optimise" that out, especially since I know PyLint and therefore Ruff [has a rule](https://docs.astral.sh/ruff/rules/unnecessary-lambda/) which would flag this.

**Pull request merged**
