### PR TITLE
Add types to `_unix_pipes`

### PR DESCRIPTION
**Pull request by harahu**
Complete type annotations for the `_unix_pipes` module.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks! This looks good, but how did you test it? Is running mypy on this file working? If so we should do it in CI too.

**Comment by harahu** [comment]
> This looks good, but how did you test it? Is running mypy on this file working?

@pquentin I tested it by running mypy on the file. It is working.

> If so we should do it in CI too.

We already are, for python 3.8 at least: https://github.com/python-trio/trio/actions/runs/3683469595/jobs/6232645740

**Comment by pquentin** [comment]
This makes sure that the annotations are valid, but not that they are complete. If tomorrow I add a new function to this file without annotations mypy won't complain about it.

It's not blocking for this pull request but we should strive to have complete annotations for each file and enforce that in CI using mypy --strict. This approach was used successfully by urllib3.

**Comment by harahu** [comment]
> It's not blocking for this pull request but we should strive to have complete annotations for each file and enforce that in CI using mypy --strict. This approach was used successfully by urllib3.

I'm aware that this technique has been used with success, and I'm a fan of introducing it. Doing so should be a separate PR. I might look into it soon.

For now, though, annotation coverage is so low that regressing coverage is the least of my worries.

**Pull request merged**
