### PR TITLE
docs: Bump year automatically

### PR DESCRIPTION
**Pull request by pquentin**

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks. I can confirm your new commit is better and works. Let's wait a bit to see what happens to https://github.com/pytest-dev/pytest/issues/3303 before merging this?

**Comment by nicoddemus** [comment]
@pquentin we will go with the same approach used here. 👍

**Comment by pquentin** [comment]
Thanks @nicoddemus for the follow-up!

@njsmith anything else to do before merging this?

**Comment by pquentin** [comment]
gentle ping

**Comment by pquentin** [comment]
Is there anything I need to do? I'm not sure why the codecov/project check is red.

**Comment by Fuyukai** [comment]
Maybe you should close this one and open another one to see if codecov fixes itself (it didn't seem to fix by close-reopening?)

**Pull request closed without merging**
