### PR TITLE
Ensure MockClock autojump never feed jump with negative values

### PR DESCRIPTION
**Pull request by touilleMan**
Fixes: #1190

### CODE REVIEW

**Comment by touilleMan** [comment]
not sure why the CI failed, any idea ?

**Comment by njsmith** [comment]
It looks like the return of the Curse of Iowa Midnight:

https://github.com/python-trio/trio/pull/911
https://developercommunity.visualstudio.com/content/problem/458410/repeated-failed-azure-pipelines-builds-due-to-incr.html

(Note: we don't actually know that Iowa is involved at all; the azure folks swear that their network looks fine at the times when this happens.)

Anyway it's an intermittent issue unrelated to your PR, so the solution here is just to rerun the tests, which I will trigger by closing and reopening the issue.

**Comment by njsmith** [comment]
@oremanj hmm, is this why you did a close/reopen earlier too?

**Comment by oremanj** [comment]
It is, and the issue persisted at that point, but probably I just hadn’t waited long enough after the failure.

**Comment by njsmith** [comment]
The change looks fine – thanks! Since it's fixing a bug, I guess it should have a newsfragment – maybe 1190.bugfix.rst, "Fix a crash that could happen when using `MockClock` with autojump enabled and a non-zero rate."

Also, not a problem here, but as a tip for the future, consider writing "[Fixes: #1190](https://help.github.com/en/articles/closing-issues-using-keywords)" instead of "Fix for #1190"

**Comment by touilleMan** [comment]
@njsmith I've added the newsfragment and corrected the "fix for" thing ;-)

**Comment by njsmith** [comment]
Awesome, thanks!

**Pull request merged**
