### PR TITLE
Temporarily disable coverage reporting on 3.8-dev

### PR DESCRIPTION
**Pull request by njsmith**
Fixes gh-711

### CODE REVIEW

**Comment by njsmith** [comment]
Oh ugh, I bet the reason codecov hasn't commented here is because it knows that this 3.8-dev job ran, and is waiting for its coverage report to arrive before commenting.

**Comment by njsmith** [comment]
Yeah, see https://docs.codecov.io/v5.0.0/docs/merging-reports#section-why-did-i-not-receive-a-notification-yet-

> Why did I not receive a notification yet?
> If CI is successful:
> * check if the reports failed to upload to Codecov.

**Comment by njsmith** [comment]
Maybe we can somehow send an empty report?

**Comment by njsmith** [comment]
So apparently if the codecov uploader doesn't find a `.coverage` file, then it doesn't upload anything (even to say "no coverage here"). (In particular: its log output on travis doesn't mention uploading a report, the way it does normally; and if you look at https://codecov.io/gh/python-trio/trio/commit/1f60eac7b0058a1af92709b7c5c431fae769971f/build there's no 3.8-dev box present.

OTOH, I guess codecov may have somehow magically figured out that the upload isn't coming? This time it did update promptly. And thinking about it, the `CHECK_FORMATTING` and `CHECK_DOCS` builds have never uploaded coverage, so it must have some kind of cleverness to handle that.... maybe it just got confused because it was the first build where 3.8-dev didn't upload coverage? Or just a random glitch that happened at a confusing moment?

**Comment by pquentin** [comment]
Surprising, but it does seem to work! Thanks.

**Pull request merged**
