### PR TITLE
Minimal changes required to get openssl v1.1.1 passing the tests

### PR DESCRIPTION
**Pull request by njsmith**
Note: this *disables* TLS v1.3 in the test suite, for now. It leaves it enabled in the library as a whole, which I'm not sure is the right choice, but maybe is OK for now since the issues we're hitting are mostly corner-cases that hopefully don't come up in real life? See https://github.com/python-trio/trio/issues/819, https://github.com/openssl/openssl/issues/7948, https://github.com/openssl/openssl/issues/7967

It also adds a test runner on openssl v1.1.1 (using azure pipelines, though not as gracefully as I was hoping: https://github.com/MicrosoftDocs/vsts-docs/issues/2939), and fixes the easy issues.

Closes: #818. Cross-ref: #817.

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks for your efforts on OpenSSL 1.1.1/TLS 1.3 tests!  but important work. 👍

codecov is saying that the hasattr branches are not covered: is this expected?

**Comment by njsmith** [comment]
@pquentin I'm really not sure what's going on with the coverage... codecov claims to be uploading it from the azure container! And of course now it's all screwed up in a different way...

**Comment by njsmith** [comment]
Huh, this is interesting... I just discovered from #827 that apparently all of the AP-provided python builds on windows are built against openssl 1.1.1. So on the one hand, the hoops this is jumping through to get openssl 1.1.1 are probably unnecessary. OTOH, supporting openssl 1.1.1 on python 3.5 is super problematic, because 3.5 is too old to have gotten the backport for `OP_NO_TLSv1_3`, so it's *impossible* to disable TLS v1.3, like this PR does...

**Comment by njsmith** [comment]
I believe this is ready to merge. The additional two "uncovered" lines are due to removing a `# pragma: no cover` on some code that checks if PyOpenSSL has TLS v1.3 support – so they were never covered in the first place, but they should be as soon as PyOpenSSL makes a release with openssl v1.1.1 support.

**Comment by njsmith** [comment]
(And I am looking forward to being able to run the test suite locally again...!)

**Comment by pquentin** [comment]
I can't load the codecov report, so I'll have to trust you on this one! The code itself looks good.

**Comment by njsmith** [comment]
Thanks! And yeah, apparently our codecov PR report pages are just completely wedged right now? I emailed codecov support about it earlier today. The individual commit reports are still working, if you can find them by manually digging through the website...

**Pull request merged**
