### PR TITLE
Simplify sockets

### PR DESCRIPTION
**Pull request by jmfrank63**
This is a first attempt to merge _socket.py with socket.py and still work in progress.
Honestly I do not really understand what has been done, but it seems the trio socket has the same symbols as the standard lib sockets. The question is are they the same.

Currently it still fails 3 tests, but the failure might give some hints in which direction to work.

The whole idea might be total crap but my experience is just start at some point and go further from there.

@njsmith @Zac-HD 
Thoughts?

### CODE REVIEW

**Comment by Zac-HD** [comment]
To be blunt I don't think this approach is going to work - it adds too many implementation details to the `trio.socket` namespace, and doesn't quite match the dynamism of the stdlib `socket` module (which has different constants on every platform...).

The least-effort way to make `trio._socket` legible to tools like `mypy` and `pylint` is probably going to be replacing the runtime namespace editing with code generation.  This is pretty easy to test though, just run the generation script in CI and fail if it produces a diff.

**Comment by jmfrank63** [comment]
Thanks @Zac-HD I'll look into this. My strategy is to use this failed attempt to see what kind of globals it produces as opposed to the original one.
I will also check if code generation is really such a good idea. I currently do not see how this could make it easier for static analysis tools to infer what is going on. Did you have something like cog in mind?

**Comment by jmfrank63** [comment]
So it is basically this list that has to be in globals():
```
['CMSG_LEN', 'CMSG_SPACE', 'CAPI', 'AF_UNSPEC', 'AF_INET', 'AF_UNIX', 'AF_IPX', 'AF_APPLETALK', 'AF_INET6', 'AF_ROUTE', 'AF_LINK', 'AF_SNA', 'PF_SYSTEM', 'AF_SYSTEM', 'SOCK_STREAM', 'SOCK_DGRAM', 'SOCK_RAW', 'SOCK_SEQPACKET', 'SOCK_RDM', 'SO_DEBUG', 'SO_ACCEPTCONN', 'SO_REUSEADDR', 'SO_KEEPALIVE', 'SO_DONTROUTE', 'SO_BROADCAST', 'SO_USELOOPBACK', 'SO_LINGER', 'SO_OOBINLINE', 'SO_REUSEPORT', 'SO_SNDBUF', 'SO_RCVBUF', 'SO_SNDLOWAT', 'SO_RCVLOWAT', 'SO_SNDTIMEO', 'SO_RCVTIMEO', 'SO_ERROR', 'SO_TYPE', 'LOCAL_PEERCRED', 'SOMAXCONN', 'SCM_RIGHTS', 'SCM_CREDS', 'MSG_OOB', 'MSG_PEEK', 'MSG_DONTROUTE', 'MSG_DONTWAIT', 'MSG_EOR', 'MSG_TRUNC', 'MSG_CTRUNC', 'MSG_WAITALL', 'MSG_EOF', 'SOL_SOCKET', 'SOL_IP', 'SOL_TCP', 'SOL_UDP', 'IPPROTO_IP', 'IPPROTO_HOPOPTS', 'IPPROTO_ICMP', 'IPPROTO_IGMP', 'IPPROTO_GGP', 'IPPROTO_IPV4', 'IPPROTO_IPV6', 'IPPROTO_IPIP', 'IPPROTO_TCP', 'IPPROTO_EGP', 'IPPROTO_PUP', 'IPPROTO_UDP', 'IPPROTO_IDP', 'IPPROTO_HELLO', 'IPPROTO_ND', 'IPPROTO_TP', 'IPPROTO_ROUTING', 'IPPROTO_FRAGMENT', 'IPPROTO_RSVP', 'IPPROTO_GRE', 'IPPROTO_ESP', 'IPPROTO_AH', 'IPPROTO_ICMPV6', 'IPPROTO_NONE', 'IPPROTO_DSTOPTS', 'IPPROTO_XTP', 'IPPROTO_EON', 'IPPROTO_PIM', 'IPPROTO_IPCOMP', 'IPPROTO_SCTP', 'IPPROTO_RAW', 'IPPROTO_MAX', 'SYSPROTO_CONTROL', 'IPPORT_RESERVED', 'IPPORT_USERRESERVED', 'INADDR_ANY', 'INADDR_BROADCAST', 'INADDR_LOOPBACK', 'INADDR_UNSPEC_GROUP', 'INADDR_ALLHOSTS_GROUP', 'INADDR_MAX_LOCAL_GROUP', 'INADDR_NONE', 'IP_OPTIONS', 'IP_HDRINCL', 'IP_TOS', 'IP_TTL', 'IP_RECVOPTS', 'IP_RECVRETOPTS', 'IP_RECVDSTADDR', 'IP_RETOPTS', 'IP_MULTICAST_IF', 'IP_MULTICAST_TTL', 'IP_MULTICAST_LOOP', 'IP_ADD_MEMBERSHIP', 'IP_DROP_MEMBERSHIP', 'IP_DEFAULT_MULTICAST_TTL', 'IP_DEFAULT_MULTICAST_LOOP', 'IP_MAX_MEMBERSHIPS', 'IPV6_JOIN_GROUP', 'IPV6_LEAVE_GROUP', 'IPV6_MULTICAST_HOPS', 'IPV6_MULTICAST_IF', 'IPV6_MULTICAST_LOOP', 'IPV6_UNICAST_HOPS', 'IPV6_V6ONLY', 'IPV6_CHECKSUM', 'IPV6_RECVTCLASS', 'IPV6_RTHDR_TYPE_0', 'IPV6_TCLASS', 'TCP_NODELAY', 'TCP_MAXSEG', 'TCP_KEEPINTVL', 'TCP_KEEPCNT', 'TCP_FASTOPEN', 'TCP_NOTSENT_LOWAT', 'EAI_ADDRFAMILY', 'EAI_AGAIN', 'EAI_BADFLAGS', 'EAI_FAIL', 'EAI_FAMILY', 'EAI_MEMORY', 'EAI_NODATA', 'EAI_NONAME', 'EAI_OVERFLOW', 'EAI_SERVICE', 'EAI_SOCKTYPE', 'EAI_SYSTEM', 'EAI_BADHINTS', 'EAI_PROTOCOL', 'EAI_MAX', 'AI_PASSIVE', 'AI_CANONNAME', 'AI_NUMERICHOST', 'AI_NUMERICSERV', 'AI_MASK', 'AI_ALL', 'AI_V4MAPPED_CFG', 'AI_ADDRCONFIG', 'AI_V4MAPPED', 'AI_DEFAULT', 'NI_MAXHOST', 'NI_MAXSERV', 'NI_NOFQDN', 'NI_NUMERICHOST', 'NI_NAMEREQD', 'NI_NUMERICSERV', 'NI_DGRAM', 'SHUT_RD', 'SHUT_WR', 'SHUT_RDWR', 'EBADF', 'EAGAIN', 'EWOULDBLOCK', '_LOCALHOST', '_LOCALHOST_V6', '_GLOBAL_DEFAULT_TIMEOUT', 'gaierror', 'herror', 'gethostname', 'ntohs', 'htonl', 'htons', 'inet_aton', 'inet_ntoa', 'inet_pton', 'inet_ntop', 'sethostname', 'if_nameindex', 'if_nametoindex', 'if_indextoname', 'set_custom_hostname_resolver', 'set_custom_socket_factory', 'getaddrinfo', 'getnameinfo', 'getprotobyname', 'from_stdlib_socket', 'fromfd', 'socketpair', 'socket', 'SocketType']
```
@Zac-HD is right, there are now symbols in there that haven't before but also a lot of symbols are missing.

**Comment by jmfrank63** [comment]
Ok, were getting closer, now import some symbols dependent on platform. That should do it.

**Comment by jmfrank63** [comment]
I'll learn every day. Obviously one shouldn't force a push, this results in a closed request :-(

**Pull request closed without merging**
