### PR TITLE
Prevent typing_extensions 4.7.0

### PR DESCRIPTION
**Pull request by A5rocks**
This is making our static tool tests fail.

### CODE REVIEW

**Comment by A5rocks** [comment]
Oh duh, CI doesn't read the actual requirements file, only the locked one. And for the locked one, pip-tools doesn't realize that it should drop the cpython-only bit?

Anyways looks like typing_extensions might make a bugfix release. Otherwise I'll uh, idk, xfail the test? We'll see in a day.

**Review by jakkdl — APPROVED** [review]

**Review by jakkdl — COMMENTED** [review]
Actually, just mark it as `skip` and we can merge it and go ahead with merging other PRs. We don't need to care about whether this gets fixed upstream or not

**Comment by jakkdl** [comment]
> And for the locked one, pip-tools doesn't realize that it should drop the cpython-only bit?

if you remove/comment out the first time `typing_extensions` is listed on line 26 it works. Playing around with it, it does not seem to be able to generate multiple different requirements in `requirements.txt` for the same package even if different lines in `test-requirements.in` are explicitly mutually exclusive.

**Comment by Fuyukai** [comment]
Why are we even testing PyPy 3.7? As far as I can tell they're not even releasing 3.7 or 3.8 builds anymore.

**Comment by jakkdl** [comment]
> Why are we even testing PyPy 3.7? As far as I can tell they're not even releasing 3.7 or 3.8 builds anymore.

we're dropping 3.7 support soon #2668 - so it's just a matter of it not having been dropped yet.

**Comment by Fuyukai** [comment]
But PyPy support is different to CPython support. PyPy dropped 3.8 already, and it dropped 3.7 quite a while ago.

**Comment by jakkdl** [comment]
Was surprisingly tricky to find what versions are supported, but yeah looks like it's [3.9 and 3.10](https://www.pypy.org/download_advanced.html). I'll drop pypy-3.8 as well in #2668 and add pypy-3.10 as well, or do that in a different PR in case it's messy.

**Comment by A5rocks** [comment]
I'm just going to wait a little before merging this to see if typing extensions releases a bugfix to fix this (they have a pr open on their side and I *think* they will?)

**Comment by A5rocks** [comment]
> Why are we even testing PyPy 3.7? As far as I can tell they're not even releasing 3.7 or 3.8 builds anymore.

Let's see what the PyPy maintainers recommend testing against! Here's where the question was asked: https://foss.heptapod.net/pypy/pypy/-/issues/3958#note_299941

**Comment by A5rocks** [comment]
Well, they merged in the bugfix 6 hours ago... but haven't made a release. Time window's up!

**Comment by A5rocks** [comment]
@jakkdl let's revert this in https://github.com/python-trio/trio/pull/2668

Additionally, could you update the README in that to say we're only going to support versions of PyPy PyPy itself still supports? (Namely 3.9 and 3.10 atm) See: https://foss.heptapod.net/pypy/pypy/-/issues/3958#note_299944

**Comment by jakkdl** [comment]
> @jakkdl let's revert this in #2668
> 
> Additionally, could you update the README in that to say we're only going to support versions of PyPy PyPy itself still supports? (Namely 3.9 and 3.10 atm) See: https://foss.heptapod.net/pypy/pypy/-/issues/3958#note_299944

It does currently say:
> **Cool, but will it work on my system?** Probably! As long as you have
some kind of Python 3.8-or-better (CPython or currently maintaned PyPy3 are
both fine), and are using Linux, macOS, Windows, or FreeBSD, then Trio
will work.

but I reworded it slightly

**Pull request merged**
