### PR TITLE
docs: fix minor code example issues

### PR DESCRIPTION
**Pull request by pohlt**
Remove redundant f-string. Replace redundant loop variable with underscore.

### CODE REVIEW

**Comment by tjstum** [comment]
Thanks for this contribution!

We're having some CI difficulties at the moment that are preventing any PRs from being merged. We're working on a workaround, and once we have that, we'll be able to move forward with this one.
It just might take a little longer than usual 😄

**Comment by tjstum** [comment]
@pohlt if you want to merge/rebase and update the branch, that would be great

**Comment by pohlt** [comment]
Happy New Year everyone!
Seems I have merge rights. Should I wait for a review of this trivial PR or just go ahead?

**Comment by tjstum** [comment]
Thanks!

**Pull request merged**
