### PR TITLE
Move docs packaging files to root

### PR DESCRIPTION
**Pull request by tjstum**
In preparation for #1026, move the requirements files to the root
directory and update the various references

### CODE REVIEW

**Comment by tjstum** [comment]
The only file left in the ci folder is `ci.sh`. Would you want to move it into the root directory as well?

**Comment by njsmith** [comment]
> The only file left in the ci folder is ci.sh. Would you want to move it into the root directory as well?

Heh, I looked at the diff first, and that was going to be my comment here, but you beat me to it :-). Yes, let's.

**Comment by tjstum** [comment]
Gentle ping on this. I think this is good to go, and then I'll rework #1026 to reference the new doc instructions

**Comment by njsmith** [comment]
Oh right, thanks :-)

**Comment by njsmith** [comment]
:tada: :birthday: And as described in our [our contributing documentation](https://trio.readthedocs.io/en/latest/contributing.html#joining-the-team), I'm sending you a Github invite now.

**Pull request merged**
