### PR TITLE
Add the ability to close a queue.

### PR DESCRIPTION
**Pull request by Fuyukai**

### CODE REVIEW

**Comment by sorcio** [comment]
I'm not sure about this change. The one part I'm specifically worried about is what is supposed to happen when the queue still holds data in its buffer. In this implementation, the getters never get a chance to consume that data. I'm not entirely sure of the full range of use cases for this API, but I can imagine that some might instead want the queue to be closed on the consuming side only when it's empty.

**Comment by smurfix** [comment]
@sorcio Seconded. A closed queue should behave like a closed file descriptor – you can read what's been sent before closing but you can't send new things.

**Comment by njsmith** [comment]
There's an ambiguity that's baked into Queue combining both the send and receive ends onto the same object. If you think of `close` as closing the put side, then it should be possible to get already-queued data. If you think of it as closing the get side, then it should discard existing data and wake up any putters with something like a `BrokenQueueError`.

One option would be to have separate `close_get` and `close_put` methods (though then you have to decide which, if any, is invoked by `with queue:`). Another would be to split the queue into two objects, as discussed in #497.

I think that probably in the long run we do want to refactor queue into a two-object design, but if you need this functionality urgently then maybe it'd be easiest to call it `close_get` (assuming that's the version you need)?

**Comment by Fuyukai** [comment]
I made it so that the get side automatically closes if there's no data and the put side is closed, because otherwise it would let the queue block forever.

**Comment by Fuyukai** [comment]
(The failing Jenkins is because Python segfaulted.)

**Comment by sorcio** [comment]
@Fuyukai there are a few cases that you're not testing and I suspect there might be a bug there. I cannot thing straight enough right now but let me just drop some notes.

1) Why not two explicitly named flags? I found it hard to track what is 0 and what is 1. You can't use `any()` but a simple `or` will do its job (and is maybe faster?)

2) You don't check for closed state in the `close_*` methods. What happens if I close twice? What happens if I call one and then the other?

3) You don't clean up the `_put_wait` and `_get_wait` collections after you send an error to waiters. I suspect there might be a situation where another operation will try to get a waiter from the list and reschedule it and break everything because we already rescheduled it with the QueueClosed exception. Maybe you can add more tests where there are multiple concurrent getters/putters.

4) small typo in the comments (size/side)

**Comment by njsmith** [comment]
I'm going to sleep on this one... in the mean time, probably anyone interested in this will also be interested in #586 :-)

**Comment by njsmith** [comment]
@Fuyukai oh right, sorry that took longer than expected... thanks for your patience here.

**Comment by njsmith** [comment]
(Oh right, and the context for the record: this is being closed in favor of #586)

**Pull request closed without merging**
