### PR TITLE
Enable flake8-pyi

### PR DESCRIPTION
**Pull request by CoolCat467**
"But wait CoolCat, why do we need pyi if we aren't shipping stubs?"
Because some of the rule checks it does look like they might help notice bugs in PRs in process.
Full rule list section: https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi

### CODE REVIEW

**Comment by A5rocks** [comment]
>   `trio/_tests/test_socket.py:31:5: PYI042 Type alias `getaddrinfoResponse` should be CamelCase`

Who's going to tell them that's pascal case, not camel case 😰

**Comment by TeamSpen210** [comment]
The float | int unions should be kept. They’re integer parameters, except they also allow `math.inf`. Maybe we should have a type alias defined somewhere to make that more explicit.

**Comment by jakkdl** [comment]
> The float | int unions should be kept. They’re integer parameters, except they also allow `math.inf`. Maybe we should have a type alias defined somewhere to make that more explicit.

+1, esp as we might possibly want to move to `int|None` at some point in the future with corresponding API deprecations.

**Comment by CoolCat467** [comment]
Planning to do another PR soon to make it `int | None` eventually, for the time being I am having the errors be ignored.

**Review by jakkdl — APPROVED** [review]

**Review by TeamSpen210 — APPROVED** [review]

**Pull request merged**
