### PR TITLE
Make measure_backlog more robust against weird errors

### PR DESCRIPTION
**Pull request by njsmith**
@nmalaguti is reporting that on a particular VPS they have access to,
sometimes, the test_open_tcp_listeners_backlog test is blowing up with
EMFILE and breaking other tests. It seems to involve the kernel
switching to using syn cookies, and then suddenly infinitely many
connection attempts can appear to succeed.

A real fix would be to make the test robust against syncookies, but
I'm not yet sure how to do that. In the mean time this at least should
make the test more robustly clean up after itself, so that this causes
a well-defined failure without shrapnel flying out to hit other tests.

### CODE REVIEW

**Comment by nmalaguti** [comment]
Just like on travis, this now causes my machine to only fail this test (but the test still fails).

```
================================================================= FAILURES ================================================================$
_____________________________________________________ test_open_tcp_listeners_backlog _____________________________________________________$

    @slow
    async def test_open_tcp_listeners_backlog():
        # Operating systems don't necessarily use the exact backlog you pass
        async def check_backlog(nominal, required_min, required_max):
            listeners = await open_tcp_listeners(0, backlog=nominal)
            actual = await measure_backlog(listeners[0])
            for listener in listeners:
                await listener.aclose()
            print("nominal ", nominal, "actual", actual)
            assert required_min <= actual <= required_max

>       await check_backlog(nominal=1, required_min=1, required_max=10)

trio/tests/test_highlevel_open_tcp_listeners.py:89:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
trio/tests/test_highlevel_open_tcp_listeners.py:83: in check_backlog
    actual = await measure_backlog(listeners[0])
trio/tests/test_highlevel_open_tcp_listeners.py:67: in measure_backlog
    client_stream = await open_stream_to_socket_listener(listener)
trio/testing/_network.py:34: in open_stream_to_socket_listener
    sock = tsocket.socket(family=family)
trio/_socket.py:342: in socket
    stdlib_socket = _stdlib_socket.socket(family, type, proto, fileno)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <socket.socket fd=-1, family=AddressFamily.AF_UNSPEC, type=0, proto=0>, family = <AddressFamily.AF_INET: 2>
type = <SocketKind.SOCK_STREAM: 1>, proto = 0, fileno = None

    def __init__(self, family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None):
        # For user code address family and type values are IntEnum members, but
        # for the underlying _socket.socket they're just integers. The
        # constructor of _socket.socket converts the given argument to an
        # integer automatically.
>       _socket.socket.__init__(self, family, type, proto, fileno)
E       OSError: [Errno 24] Too many open files

/usr/lib/python3.6/socket.py:144: OSError
============================================= 1 failed, 397 passed, 2 skipped in 11.24 seconds =============================================
sys:1: ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 43479)>
sys:1: ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_INET6, type=2049, proto=6, laddr=('::', 40433, 0, 0)>
```

From the kernel logs:

```
$ sudo dmesg | tail -1
[ 5071.268199] TCP: request_sock_TCP: Possible SYN flooding on port 43479. Sending cookies.  Check SNMP counters.
```

**Comment by njsmith** [comment]
I should probably leave a link here to the chat where we debugged a bunch of this, for any future archaeologists: https://gitter.im/python-trio/general?at=5a08e2b1505b630c05d53b89

**Comment by njsmith** [comment]
Okay, since I can't think of any way to run this test once syn cookies come into play, I've updated it further to put an upper bound on how many connection attempts are made, and if we hit that we consider the test to have passed. (But, sneakily, we don't cover all the lines this way, so hopefully we'll get some warning if we ever end up in a situation where *all* our test runners are giving up and effectively skipping the test.)

@nmalaguti What do you think?

**Comment by nmalaguti** [comment]
It would be nice to someday have a way of detecting that the backlog was triggered rather than using a timeout (to avoid syn cookie weirdness), but this now passes on my linux box. This seems like a fair hack to avoid file descriptor/ephemeral port exhaustion and "infinite" backlog.

LGTM 👍.

**Comment by njsmith** [comment]
👏

**Pull request merged**
