### PR TITLE
Remove special handling due to IPython lacking support for exception groups

### PR DESCRIPTION
**Pull request by jakkdl**
Quick draft request I'll look over later in case it needs further fixes, but IPython now has a workaround for displaying exceptiongroups, and the comment said this section could be removed in that case. https://github.com/ipython/ipython/issues/13753

EDIT: I guess it needs a release too, and we'd need to bump the IPython requirement to that as well - so this will have to languish for quite a while.

### CODE REVIEW

**Comment by A5rocks** [comment]
I retargeted this PR to the PR that bumps dependencies and went ahead and marked this as reviewable: I think you will need to remove a test (or at least update it) but I believe this fixes the CI for that other PR.

**Comment by A5rocks** [comment]
Sorry, I just realize I was mistaken. Your fix hasn't gone out, I just jumped the gun when I saw multierrors were formatting differently!

**Comment by jakkdl** [comment]
> Sorry, I just realize I was mistaken. Your fix hasn't gone out, I just jumped the gun when I saw multierrors were formatting differently!

Ah sorry, maybe could've been a bit clearer in my edit :)

> Additionally, it seems I can't force-push my merge above out:
> 
> ```
> @A5rocks ➜ /workspaces/trio (ipython_exceptiongroup_support) $ git push --force
> remote: Permission to jakkdl/trio.git denied to A5rocks.
> fatal: unable to access 'https://github.com/jakkdl/trio/': The requested URL returned error: 403
> ```
> 
> :(

Added you as a collaborator to the fork, think that might help? I could maybe start pushing branches to the `trio/` repository otherwise, but I suspect force-pushing from other people isn't gonna come up too many more times.

**Comment by A5rocks** [comment]
Yeah I don't think that'll happen again: I'll try not to jump to conclusions next time!

**Comment by jakkdl** [comment]
> Yeah I don't think that'll happen again: I'll try not to jump to conclusions next time!
> 
> EDIT: I don't need to join your repo FWIW, you can force push yourself xd (since you're here, I just wanted to decrease the work I caused!)

Ah, you can just push reversion commits then. `git revert` is very handy

**Comment by Zac-HD** [comment]
[IPython 8.15 is has been released](https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-15) with native `ExceptionGroup` support, so let's rebase this PR and get it in before Trio 0.23 🚀

**Comment by Zac-HD** [comment]
Looks like we just need to delete `trio/_core/_tests/test_multierror.py::test_ipython_exc_handler` and `test_ipython_custom_exc_handler`, and add a changelog, then we'll be ready to merge!

(and maybe also [enable skip-covered in `.coveragerc`](https://coverage.readthedocs.io/en/stable/config.html#report-skip-covered) so it's easier to find out what failed next time)

**Review by TeamSpen210 — APPROVED** [review]

**Comment by jakkdl** [comment]
@TeamSpen210 mind adding a changelog entry as well?

**Review by Zac-HD — APPROVED** [review]
+5 / -198 🤩

**Pull request merged**
